# SPDX-FileCopyrightText: The terraform-provider-k8s Authors
# SPDX-License-Identifier: 0BSD

FROM metio/devcontainers-go:latest

RUN go install github.com/hashicorp/terraform@main
RUN go install gotest.tools/gotestsum@latest
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@master
