/*
 * SPDX-FileCopyrightText: The terraform-provider-k8s Authors
 * SPDX-License-Identifier: 0BSD
 */

package fetcher

var CRDv1Sources = []UpstreamSource{
	{
		ProjectName: "3scale/apicast-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/3scale/apicast-operator/blob/master/config/crd/bases/apps.3scale.net_apicasts.yaml",
		},
	},
	{
		ProjectName: "aerospike/aerospike-kubernetes-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aerospike/aerospike-kubernetes-operator/blob/master/config/crd/bases/asdb.aerospike.com_aerospikeclusters.yaml",
		},
	},
	{
		ProjectName: "Alvearie/imaging-ingestion",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/Alvearie/imaging-ingestion/blob/main/imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dicomeventbridges.yaml",
			"https://github.com/Alvearie/imaging-ingestion/blob/main/imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dicomeventdriveningestions.yaml",
			"https://github.com/Alvearie/imaging-ingestion/blob/main/imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dicominstancebindings.yaml",
			"https://github.com/Alvearie/imaging-ingestion/blob/main/imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dicomstudybindings.yaml",
			"https://github.com/Alvearie/imaging-ingestion/blob/main/imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dicomwebingestionservices.yaml",
			"https://github.com/Alvearie/imaging-ingestion/blob/main/imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dimseingestionservices.yaml",
			"https://github.com/Alvearie/imaging-ingestion/blob/main/imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dimseproxies.yaml",
		},
	},
	{
		ProjectName: "apache/camel-k",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_builds.yaml",
			"https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_camelcatalogs.yaml",
			"https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_integrationkits.yaml",
			"https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_integrationplatforms.yaml",
			"https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_integrations.yaml",
			"https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_kameletbindings.yaml",
			"https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_kamelets.yaml",
		},
	},
	{
		ProjectName: "apache/flink-kubernetes-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/apache/flink-kubernetes-operator/blob/main/helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml",
			"https://github.com/apache/flink-kubernetes-operator/blob/main/helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml",
		},
	},
	{
		ProjectName: "apache/rocketmq-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/apache/rocketmq-operator/blob/master/deploy/crds/rocketmq.apache.org_brokers.yaml",
			"https://github.com/apache/rocketmq-operator/blob/master/deploy/crds/rocketmq.apache.org_consoles.yaml",
			"https://github.com/apache/rocketmq-operator/blob/master/deploy/crds/rocketmq.apache.org_nameservices.yaml",
			"https://github.com/apache/rocketmq-operator/blob/master/deploy/crds/rocketmq.apache.org_topictransfers.yaml",
		},
	},
	{
		ProjectName: "Apicurio/apicurio-registry-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/Apicurio/apicurio-registry-operator/blob/main/config/crd/resources/registry.apicur.io_apicurioregistries.yaml",
		},
	},
	{
		ProjectName: "apimatic/apimatic-kubernetes-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/apimatic/apimatic-kubernetes-operator/blob/main/config/crd/bases/apicodegen.apimatic.io_apimatics.yaml",
		},
	},
	{
		ProjectName: "aquasecurity/aqua-operator",
		License:     aqua,
		URLs: []string{
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/aquasecurity.github.io_aquastarboards.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/aquasecurity.github.io_clusterconfigauditreports.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/aquasecurity.github.io_configauditreports.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/operator.aquasec.com_aquacsps.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/operator.aquasec.com_aquadatabases.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/operator.aquasec.com_aquaenforcers.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/operator.aquasec.com_aquagateways.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/operator.aquasec.com_aquakubeenforcers.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/operator.aquasec.com_aquascanners.yaml",
			"https://github.com/aquasecurity/aqua-operator/blob/master/config/crd/bases/operator.aquasec.com_aquaservers.yaml",
		},
	},
	{
		ProjectName: "argoproj-labs/argocd-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/argoproj-labs/argocd-operator/blob/master/config/crd/bases/argoproj.io_applications.yaml",
			"https://github.com/argoproj-labs/argocd-operator/blob/master/config/crd/bases/argoproj.io_applicationsets.yaml",
			"https://github.com/argoproj-labs/argocd-operator/blob/master/config/crd/bases/argoproj.io_appprojects.yaml",
			"https://github.com/argoproj-labs/argocd-operator/blob/master/config/crd/bases/argoproj.io_argocdexports.yaml",
			"https://github.com/argoproj-labs/argocd-operator/blob/master/config/crd/bases/argoproj.io_argocds.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/apigatewayv2-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/config/crd/bases/apigatewayv2.services.k8s.aws_apis.yaml",
			"https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/config/crd/bases/apigatewayv2.services.k8s.aws_authorizers.yaml",
			"https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/config/crd/bases/apigatewayv2.services.k8s.aws_deployments.yaml",
			"https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/config/crd/bases/apigatewayv2.services.k8s.aws_integrations.yaml",
			"https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/config/crd/bases/apigatewayv2.services.k8s.aws_routes.yaml",
			"https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/config/crd/bases/apigatewayv2.services.k8s.aws_stages.yaml",
			"https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/config/crd/bases/apigatewayv2.services.k8s.aws_vpclinks.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/applicationautoscaling-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/applicationautoscaling-controller/blob/main/config/crd/bases/applicationautoscaling.services.k8s.aws_scalabletargets.yaml",
			"https://github.com/aws-controllers-k8s/applicationautoscaling-controller/blob/main/config/crd/bases/applicationautoscaling.services.k8s.aws_scalingpolicies.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/dynamodb-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/dynamodb-controller/blob/main/config/crd/bases/dynamodb.services.k8s.aws_backups.yaml",
			"https://github.com/aws-controllers-k8s/dynamodb-controller/blob/main/config/crd/bases/dynamodb.services.k8s.aws_globaltables.yaml",
			"https://github.com/aws-controllers-k8s/dynamodb-controller/blob/main/config/crd/bases/dynamodb.services.k8s.aws_tables.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/ec2-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_dhcpoptions.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_elasticipaddresses.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_instances.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_internetgateways.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_natgateways.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_routetables.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_securitygroups.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_subnets.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_transitgateways.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_vpcendpoints.yaml",
			"https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_vpcs.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/ecr-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/ecr-controller/blob/main/config/crd/bases/ecr.services.k8s.aws_pullthroughcacherules.yaml",
			"https://github.com/aws-controllers-k8s/ecr-controller/blob/main/config/crd/bases/ecr.services.k8s.aws_repositories.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/eks-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/crd/bases/eks.services.k8s.aws_addons.yaml",
			"https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/crd/bases/eks.services.k8s.aws_clusters.yaml",
			"https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/crd/bases/eks.services.k8s.aws_fargateprofiles.yaml",
			"https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/crd/bases/eks.services.k8s.aws_nodegroups.yaml",
			"https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/crd/common/bases/services.k8s.aws_adoptedresources.yaml",
			"https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/crd/common/bases/services.k8s.aws_fieldexports.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/elasticache-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/crd/bases/elasticache.services.k8s.aws_cacheparametergroups.yaml",
			"https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/crd/bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml",
			"https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml",
			"https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/crd/bases/elasticache.services.k8s.aws_snapshots.yaml",
			"https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/crd/bases/elasticache.services.k8s.aws_usergroups.yaml",
			"https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/crd/bases/elasticache.services.k8s.aws_users.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/emrcontainers-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/emrcontainers-controller/blob/main/config/crd/bases/emrcontainers.services.k8s.aws_jobruns.yaml",
			"https://github.com/aws-controllers-k8s/emrcontainers-controller/blob/main/config/crd/bases/emrcontainers.services.k8s.aws_virtualclusters.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/iam-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/iam-controller/blob/main/config/crd/bases/iam.services.k8s.aws_groups.yaml",
			"https://github.com/aws-controllers-k8s/iam-controller/blob/main/config/crd/bases/iam.services.k8s.aws_policies.yaml",
			"https://github.com/aws-controllers-k8s/iam-controller/blob/main/config/crd/bases/iam.services.k8s.aws_roles.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/kms-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/kms-controller/blob/main/config/crd/bases/kms.services.k8s.aws_aliases.yaml",
			"https://github.com/aws-controllers-k8s/kms-controller/blob/main/config/crd/bases/kms.services.k8s.aws_grants.yaml",
			"https://github.com/aws-controllers-k8s/kms-controller/blob/main/config/crd/bases/kms.services.k8s.aws_keys.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/lambda-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/lambda-controller/blob/main/config/crd/bases/lambda.services.k8s.aws_aliases.yaml",
			"https://github.com/aws-controllers-k8s/lambda-controller/blob/main/config/crd/bases/lambda.services.k8s.aws_codesigningconfigs.yaml",
			"https://github.com/aws-controllers-k8s/lambda-controller/blob/main/config/crd/bases/lambda.services.k8s.aws_eventsourcemappings.yaml",
			"https://github.com/aws-controllers-k8s/lambda-controller/blob/main/config/crd/bases/lambda.services.k8s.aws_functions.yaml",
			"https://github.com/aws-controllers-k8s/lambda-controller/blob/main/config/crd/bases/lambda.services.k8s.aws_functionurlconfigs.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/mq-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/mq-controller/blob/main/config/crd/bases/mq.services.k8s.aws_brokers.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/opensearchservice-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/opensearchservice-controller/blob/main/config/crd/bases/opensearchservice.services.k8s.aws_domains.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/prometheusservice-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/prometheusservice-controller/blob/main/config/crd/bases/prometheusservice.services.k8s.aws_alertmanagerdefinitions.yaml",
			"https://github.com/aws-controllers-k8s/prometheusservice-controller/blob/main/config/crd/bases/prometheusservice.services.k8s.aws_rulegroupsnamespaces.yaml",
			"https://github.com/aws-controllers-k8s/prometheusservice-controller/blob/main/config/crd/bases/prometheusservice.services.k8s.aws_workspaces.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/rds-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_dbclusterparametergroups.yaml",
			"https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_dbclusters.yaml",
			"https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_dbinstances.yaml",
			"https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_dbparametergroups.yaml",
			"https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_dbproxies.yaml",
			"https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_dbsubnetgroups.yaml",
			"https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_globalclusters.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/s3-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/s3-controller/blob/main/config/crd/bases/s3.services.k8s.aws_buckets.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/sagemaker-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_apps.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_dataqualityjobdefinitions.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_domains.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_endpointconfigs.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_endpoints.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_featuregroups.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_hyperparametertuningjobs.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_modelbiasjobdefinitions.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_modelexplainabilityjobdefinitions.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_modelpackagegroups.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_modelpackages.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_modelqualityjobdefinitions.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_models.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_monitoringschedules.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_notebookinstancelifecycleconfigs.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_notebookinstances.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_processingjobs.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_trainingjobs.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_transformjobs.yaml",
			"https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_userprofiles.yaml",
		},
	},
	{
		ProjectName: "aws-controllers-k8s/sfn-controlle",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/aws-controllers-k8s/sfn-controller/blob/main/config/crd/bases/sfn.services.k8s.aws_activities.yaml",
			"https://github.com/aws-controllers-k8s/sfn-controller/blob/main/config/crd/bases/sfn.services.k8s.aws_statemachines.yaml",
		},
	},
	{
		ProjectName: "bitnami-labs/sealed-secrets",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml",
		},
	},
	{
		ProjectName: "carlosedp/lbconfig-operator",
		License:     mit,
		URLs: []string{
			"https://github.com/carlosedp/lbconfig-operator/blob/main/config/crd/bases/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml",
		},
	},
	{
		ProjectName: "cert-manager/cert-manager",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-certificaterequests.yaml",
			"https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-certificates.yaml",
			"https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-challenges.yaml",
			"https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-clusterissuers.yaml",
			"https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-issuers.yaml",
			"https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-orders.yaml",
		},
	},
	{
		ProjectName: "chaos-mesh/chaos-mesh",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_awschaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_azurechaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_blockchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_dnschaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_gcpchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_httpchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_iochaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_jvmchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_kernelchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_networkchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_physicalmachinechaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_physicalmachines.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_podchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_podhttpchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_podiochaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_podnetworkchaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_remoteclusters.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_schedules.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_statuschecks.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_stresschaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_timechaos.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_workflownodes.yaml",
			"https://github.com/chaos-mesh/chaos-mesh/blob/master/config/crd/bases/chaos-mesh.org_workflows.yaml",
		},
	},
	{
		ProjectName: "che-incubator/kubernetes-image-puller-operator",
		License:     eplV2,
		URLs: []string{
			"https://github.com/che-incubator/kubernetes-image-puller-operator/blob/main/config/crd/bases/che.eclipse.org_kubernetesimagepullers.yaml",
		},
	},
	{
		ProjectName: "cilium/cilium",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumclusterwideenvoyconfigs.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumclusterwidenetworkpolicies.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumegressgatewaypolicies.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumendpoints.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumenvoyconfigs.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumexternalworkloads.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumidentities.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumlocalredirectpolicies.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumnetworkpolicies.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumnodes.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumbgppeeringpolicies.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumcidrgroups.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumendpointslices.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliuml2announcementpolicies.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumloadbalancerippools.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumnodeconfigs.yaml",
			"https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumpodippools.yaml",
		},
	},
	{
		ProjectName: "clastix/capsule",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/clastix/capsule/blob/master/config/crd/bases/capsule.clastix.io_capsuleconfigurations.yaml",
			"https://github.com/clastix/capsule/blob/master/config/crd/bases/capsule.clastix.io_tenants.yaml",
		},
	},
	{
		ProjectName: "cloud-bulldozer/benchmark-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/cloud-bulldozer/benchmark-operator/blob/master/config/crd/bases/ripsaw.cloudbulldozer.io_benchmarks.yaml",
		},
	},
	{
		ProjectName: "clusternet/clusternet",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_bases.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_descriptions.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_feedinventories.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_globalizations.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_helmcharts.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_helmreleases.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_localizations.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_manifests.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/apps.clusternet.io_subscriptions.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/clusters.clusternet.io_clusterregistrationrequests.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/clusters.clusternet.io_managedclusters.yaml",
			"https://github.com/clusternet/clusternet/blob/main/manifests/crds/nodefeaturerule-crd.yaml",
		},
	},
	{
		ProjectName: "clusterpedia-io/clusterpedia",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/clusterpedia-io/clusterpedia/blob/main/kustomize/crds/cluster.clusterpedia.io_clustersyncresources.yaml",
			"https://github.com/clusterpedia-io/clusterpedia/blob/main/kustomize/crds/cluster.clusterpedia.io_pediaclusters.yaml",
			"https://github.com/clusterpedia-io/clusterpedia/blob/main/kustomize/crds/policy.clusterpedia.io_clusterimportpolicies.yaml",
			"https://github.com/clusterpedia-io/clusterpedia/blob/main/kustomize/crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml",
		},
	},
	{
		ProjectName: "composable-operator/composable",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/composable-operator/composable/blob/main/config/crd/bases/ibmcloud.ibm.com_composables.yaml",
		},
	},
	{
		ProjectName: "couchbase-partners/helm-charts",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/couchbase-partners/helm-charts/blob/master/charts/couchbase-operator/crds/couchbase.crds.yaml",
		},
	},
	{
		ProjectName: "crossplane/crossplane",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/apiextensions.crossplane.io_compositions.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/pkg.crossplane.io_configurationrevisions.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/pkg.crossplane.io_configurations.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/pkg.crossplane.io_controllerconfigs.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/pkg.crossplane.io_locks.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/pkg.crossplane.io_providerrevisions.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/pkg.crossplane.io_providers.yaml",
			"https://github.com/crossplane/crossplane/blob/master/cluster/crds/secrets.crossplane.io_storeconfigs.yaml",
		},
	},
	{
		ProjectName: "CrunchyData/postgres-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/CrunchyData/postgres-operator/blob/master/config/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml",
		},
	},
	{
		ProjectName: "cryostatio/cryostat-operator",
		License:     uplV1,
		URLs: []string{
			"https://github.com/cryostatio/cryostat-operator/blob/main/config/crd/bases/operator.cryostat.io_cryostats.yaml",
		},
	},
	{
		ProjectName: "ctron/ditto-operator",
		License:     eplV2,
		URLs: []string{
			"https://github.com/ctron/ditto-operator/blob/main/helm/ditto-operator/crds/ditto.yaml",
		},
	},
	{
		ProjectName: "ctron/hawkbit-operator",
		License:     eplV2,
		URLs: []string{
			"https://github.com/ctron/hawkbit-operator/blob/main/crds/hawkbit.crd.yaml",
		},
	},
	{
		ProjectName: "dexidp/dex",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/authcodes.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/authrequests.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/connectors.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/devicerequests.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/devicetokens.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/oauth2clients.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/offlinesessionses.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/passwords.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/refreshtokens.yaml",
			"https://github.com/dexidp/dex/blob/master/scripts/manifests/crds/signingkeies.yaml",
		},
	},
	{
		ProjectName: "digitalis-io/vals-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/digitalis-io/vals-operator/blob/main/config/crd/bases/digitalis.io_dbsecrets.yaml",
			"https://github.com/digitalis-io/vals-operator/blob/main/config/crd/bases/digitalis.io_valssecrets.yaml",
		},
	},
	{
		ProjectName: "dmesser/cockroachdb-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/dmesser/cockroachdb-operator/blob/main/config/crd/bases/charts.operatorhub.io_cockroachdbs.yaml",
		},
	},
	{
		ProjectName: "eclipse-che/che-operator",
		License:     eplV2,
		URLs: []string{
			"https://github.com/eclipse-che/che-operator/blob/main/config/crd/bases/org.eclipse.che_checlusters.yaml",
		},
	},
	{
		ProjectName: "elastic/cloud-on-k8s",
		License:     elastic,
		URLs: []string{
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml",
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/apm.k8s.elastic.co_apmservers.yaml",
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/autoscaling.k8s.elastic.co_elasticsearchautoscalers.yaml",
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/beat.k8s.elastic.co_beats.yaml",
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml",
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml",
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/kibana.k8s.elastic.co_kibanas.yaml",
			"https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/maps.k8s.elastic.co_elasticmapsservers.yaml",
		},
	},
	{
		ProjectName: "emissary-ingress/emissary",
		License:     mit,
		URLs: []string{
			"https://github.com/emissary-ingress/emissary/blob/master/pkg/api/getambassador.io/crds.yaml",
		},
	},
	{
		ProjectName: "external-secrets/external-secrets",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml",
			"https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_clustersecretstores.yaml",
			"https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_externalsecrets.yaml",
			"https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_secretstores.yaml",
		},
	},
	{
		ProjectName: "Flagsmith/flagsmith-operator",
		License:     flagsmith,
		URLs: []string{
			"https://github.com/Flagsmith/flagsmith-operator/blob/master/config/crd/bases/charts.flagsmith.com_flagsmiths.yaml",
		},
	},
	{
		ProjectName: "fluid-cloudnative/fluid",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_alluxioruntimes.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_databackups.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_dataloads.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_datasets.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_goosefsruntimes.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_jindoruntimes.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_juicefsruntimes.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml",
			"https://github.com/fluid-cloudnative/fluid/blob/master/config/crd/bases/data.fluid.io_thinruntimes.yaml",
		},
	},
	{
		ProjectName: "fluxcd/flagger",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluxcd/flagger/blob/main/artifacts/flagger/crd.yaml",
		},
	},
	{
		ProjectName: "fluxcd/helm-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluxcd/helm-controller/blob/main/config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml",
		},
	},
	{
		ProjectName: "fluxcd/image-automation-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluxcd/image-automation-controller/blob/main/config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml",
		},
	},
	{
		ProjectName: "fluxcd/image-reflector-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluxcd/image-reflector-controller/blob/main/config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml",
			"https://github.com/fluxcd/image-reflector-controller/blob/main/config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml",
		},
	},
	{
		ProjectName: "fluxcd/kustomize-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluxcd/kustomize-controller/blob/main/config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml",
		},
	},
	{
		ProjectName: "fluxcd/notification-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluxcd/notification-controller/blob/main/config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml",
			"https://github.com/fluxcd/notification-controller/blob/main/config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml",
			"https://github.com/fluxcd/notification-controller/blob/main/config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml",
		},
	},
	{
		ProjectName: "fluxcd/source-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fluxcd/source-controller/blob/main/config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml",
			"https://github.com/fluxcd/source-controller/blob/main/config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml",
			"https://github.com/fluxcd/source-controller/blob/main/config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml",
			"https://github.com/fluxcd/source-controller/blob/main/config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml",
			"https://github.com/fluxcd/source-controller/blob/main/config/crd/bases/source.toolkit.fluxcd.io_ocirepositories.yaml",
		},
	},
	{
		ProjectName: "fossul/fossul",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/fossul/fossul/blob/master/operator/config/crd/bases/fossul.io_backupconfigs.yaml",
			"https://github.com/fossul/fossul/blob/master/operator/config/crd/bases/fossul.io_backups.yaml",
			"https://github.com/fossul/fossul/blob/master/operator/config/crd/bases/fossul.io_backupschedules.yaml",
			"https://github.com/fossul/fossul/blob/master/operator/config/crd/bases/fossul.io_fossuls.yaml",
			"https://github.com/fossul/fossul/blob/master/operator/config/crd/bases/fossul.io_restores.yaml",
		},
	},
	{
		ProjectName: "furiko-io/furiko",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/furiko-io/furiko/blob/main/config/crd/bases/execution.furiko.io_jobconfigs.yaml",
			"https://github.com/furiko-io/furiko/blob/main/config/crd/bases/execution.furiko.io_jobs.yaml",
		},
	},
	{
		ProjectName: "gitlab-org/cloud-native/gitlab-operator",
		License:     apacheV2,
		URLs: []string{
			"https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/master/config/crd/bases/apps.gitlab.com_gitlabs.yaml",
		},
	},
	{
		ProjectName: "gitlab-org/gl-openshift/gitlab-runner-operator",
		License:     apacheV2,
		URLs: []string{
			"https://gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/-/blob/master/config/crd_k8s/bases/apps.gitlab.com_runners.yaml",
		},
	},
	{
		ProjectName: "GoogleCloudPlatform/spark-on-k8s-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml",
			"https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml",
		},
	},
	{
		ProjectName: "grafana-operator/grafana-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/grafana-operator/grafana-operator/blob/master/config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml",
			"https://github.com/grafana-operator/grafana-operator/blob/master/config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml",
			"https://github.com/grafana-operator/grafana-operator/blob/master/config/crd/bases/grafana.integreatly.org_grafanafolders.yaml",
			"https://github.com/grafana-operator/grafana-operator/blob/master/config/crd/bases/grafana.integreatly.org_grafanas.yaml",
		},
	},
	{
		ProjectName: "grafana/loki",
		License:     agplV3only,
		URLs: []string{
			"https://github.com/grafana/loki/blob/main/operator/config/crd/bases/config.grafana.com_projectconfigs.yaml",
			"https://github.com/grafana/loki/blob/main/operator/config/crd/bases/loki.grafana.com_alertingrules.yaml",
			"https://github.com/grafana/loki/blob/main/operator/config/crd/bases/loki.grafana.com_lokistacks.yaml",
			"https://github.com/grafana/loki/blob/main/operator/config/crd/bases/loki.grafana.com_recordingrules.yaml",
			"https://github.com/grafana/loki/blob/main/operator/config/crd/bases/loki.grafana.com_rulerconfigs.yaml",
		},
	},
	{
		ProjectName: "gravitational/teleport",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_githubconnectors.yaml",
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_loginrules.yaml",
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_oidcconnectors.yaml",
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_oktaimportrules.yaml",
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_provisiontokens.yaml",
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml",
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_samlconnectors.yaml",
			"https://github.com/gravitational/teleport/blob/master/integrations/operator/config/crd/bases/resources.teleport.dev_users.yaml",
		},
	},
	{
		ProjectName: "hazelcast/hazelcast-platform-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/hazelcast/hazelcast-platform-operator/blob/main/config/crd/bases/hazelcast.com_cronhotbackups.yaml",
			"https://github.com/hazelcast/hazelcast-platform-operator/blob/main/config/crd/bases/hazelcast.com_hazelcasts.yaml",
			"https://github.com/hazelcast/hazelcast-platform-operator/blob/main/config/crd/bases/hazelcast.com_hotbackups.yaml",
			"https://github.com/hazelcast/hazelcast-platform-operator/blob/main/config/crd/bases/hazelcast.com_managementcenters.yaml",
			"https://github.com/hazelcast/hazelcast-platform-operator/blob/main/config/crd/bases/hazelcast.com_maps.yaml",
			"https://github.com/hazelcast/hazelcast-platform-operator/blob/main/config/crd/bases/hazelcast.com_wanreplications.yaml",
		},
	},
	{
		ProjectName: "Hyperfoil/horreum-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/Hyperfoil/horreum-operator/blob/master/config/crd/bases/hyperfoil.io_horreums.yaml",
		},
	},
	{
		ProjectName: "Hyperfoil/hyperfoil-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/Hyperfoil/hyperfoil-operator/blob/master/config/crd/bases/hyperfoil.io_hyperfoils.yaml",
		},
	},
	{
		ProjectName: "IBM/varnish-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/IBM/varnish-operator/blob/main/config/crd/bases/caching.ibm.com_varnishclusters.yaml",
		},
	},
	{
		ProjectName: "infinispan/infinispan-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/infinispan/infinispan-operator/blob/main/config/crd/bases/infinispan.org_infinispans.yaml",
			"https://github.com/infinispan/infinispan-operator/blob/main/config/crd/bases/infinispan.org_backups.yaml",
			"https://github.com/infinispan/infinispan-operator/blob/main/config/crd/bases/infinispan.org_batches.yaml",
			"https://github.com/infinispan/infinispan-operator/blob/main/config/crd/bases/infinispan.org_caches.yaml",
			"https://github.com/infinispan/infinispan-operator/blob/main/config/crd/bases/infinispan.org_restores.yaml",
		},
	},
	{
		ProjectName: "istio/istio",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/istio/istio/blob/master/manifests/charts/base/crds/crd-all.gen.yaml",
			"https://github.com/istio/istio/blob/master/manifests/charts/base/crds/crd-operator.yaml",
		},
	},
	{
		ProjectName: "jaegertracing/jaeger-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/jaegertracing/jaeger-operator/blob/main/config/crd/bases/jaegertracing.io_jaegers.yaml",
		},
	},
	{
		ProjectName: "k8gb-io/k8gb",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/k8gb-io/k8gb/blob/master/chart/k8gb/crd/dns-endpoint-crd-manifest.yaml",
			"https://github.com/k8gb-io/k8gb/blob/master/chart/k8gb/crd/k8gb.absa.oss_gslbs.yaml",
		},
	},
	{
		ProjectName: "karmada-io/karmada",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/multicluster/multicluster.x-k8s.io_serviceexports.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/multicluster/multicluster.x-k8s.io_serviceimports.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml",
			"https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/work/work.karmada.io_works.yaml",
		},
	},
	{
		ProjectName: "kedacore/keda",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kedacore/keda/blob/main/config/crd/bases/keda.sh_clustertriggerauthentications.yaml",
			"https://github.com/kedacore/keda/blob/main/config/crd/bases/keda.sh_scaledjobs.yaml",
			"https://github.com/kedacore/keda/blob/main/config/crd/bases/keda.sh_scaledobjects.yaml",
			"https://github.com/kedacore/keda/blob/main/config/crd/bases/keda.sh_triggerauthentications.yaml",
		},
	},
	{
		ProjectName: "keycloak/keycloak-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloakbackups_crd.yaml",
			"https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloakclients_crd.yaml",
			"https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloakrealms_crd.yaml",
			"https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml",
			"https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloakusers_crd.yaml",
		},
	},
	{
		ProjectName: "kiali/kiali-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kiali/kiali-operator/blob/master/crd-docs/crd/kiali.io_kialis.yaml",
		},
	},
	{
		ProjectName: "kiegroup/kogito-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kiegroup/kogito-operator/blob/main/config/crd/app/bases/app.kiegroup.org_kogitobuilds.yaml",
			"https://github.com/kiegroup/kogito-operator/blob/main/config/crd/app/bases/app.kiegroup.org_kogitoinfras.yaml",
			"https://github.com/kiegroup/kogito-operator/blob/main/config/crd/app/bases/app.kiegroup.org_kogitoruntimes.yaml",
			"https://github.com/kiegroup/kogito-operator/blob/main/config/crd/app/bases/app.kiegroup.org_kogitosupportingservices.yaml",
		},
	},
	{
		ProjectName: "knative/operator",
		License:     apacheV2,
		URLs: []string{
			"https://raw.githubusercontent.com/knative/operator/main/config/crd/bases/operator.knative.dev_knativeeventings.yaml",
			"https://raw.githubusercontent.com/knative/operator/main/config/crd/bases/operator.knative.dev_knativeservings.yaml",
		},
	},
	{
		ProjectName: "koordinator-sh/koordinator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/config.koordinator.sh_clustercolocationprofiles.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/scheduling.koordinator.sh_devices.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/scheduling.koordinator.sh_podmigrationjobs.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/scheduling.koordinator.sh_reservations.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/scheduling.sigs.k8s.io_elasticquotas.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/scheduling.sigs.k8s.io_podgroups.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/slo.koordinator.sh_nodemetrics.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/slo.koordinator.sh_nodeslos.yaml",
			"https://github.com/koordinator-sh/koordinator/blob/main/config/crd/bases/topology.node.k8s.io_noderesourcetopologies.yaml",
		},
	},
	{
		ProjectName: "ktsstudio/mirrors",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/ktsstudio/mirrors/blob/main/config/crd/bases/mirrors.kts.studio_secretmirrors.yaml",
		},
	},
	{
		ProjectName: "kube-logging/logging-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging-extensions.banzaicloud.io_eventtailers.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_flows.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusterflows.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_syslogngflows.yaml",
			"https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml",
		},
	},
	{
		ProjectName: "kubedl-io/kubedl",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/apps.kubedl.io_crons.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/cache.kubedl.io_cachebackends.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/inference.kubedl.io_elasticbatchjobs.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/model.kubedl.io_models.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/model.kubedl.io_modelversions.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/notebook.kubedl.io_notebooks.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/serving.kubedl.io_inferences.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/training.kubedl.io_elasticdljobs.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/training.kubedl.io_marsjobs.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/training.kubedl.io_mpijobs.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/training.kubedl.io_pytorchjobs.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/training.kubedl.io_tfjobs.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/training.kubedl.io_xdljobs.yaml",
			"https://github.com/kubedl-io/kubedl/blob/master/config/crd/bases/training.kubedl.io_xgboostjobs.yaml",
		},
	},
	{
		ProjectName: "kubeedge/kubeedge",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/apps_v1alpha1_nodegroup.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/cluster_objectsync_v1alpha1.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/devices_v1alpha2_device.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/devices_v1alpha2_devicemodel.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/objectsync_v1alpha1.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/operations_v1alpha1_nodeupgradejob.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/router_v1_rule.yaml",
			"https://github.com/kubeedge/kubeedge/blob/master/manifests/charts/cloudcore/crds/router_v1_ruleEndpoint.yaml",
		},
	},
	{
		ProjectName: "kubernetes-sigs/aws-load-balancer-controller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml",
			"https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml",
		},
	},
	{
		ProjectName: "kubernetes-sigs/gateway-api",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml",
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_gateways.yaml",
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml",
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml",
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml",
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml",
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml",
			"https://github.com/kubernetes-sigs/gateway-api/blob/main/config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml",
		},
	},
	{
		ProjectName: "kubernetes-sigs/security-profiles-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/apparmorprofile.yaml",
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/profilebinding.yaml",
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/profilerecording.yaml",
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/securityprofilenodestatus.yaml",
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/securityprofilesoperatordaemon.yaml",
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/selinuxpolicy.yaml",
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/selinuxpolicy.yaml",
			"https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/base-crds/crds/seccompprofile.yaml",
		},
	},
	{
		ProjectName: "kubernetes/autoscaler",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml",
		},
	},
	{
		ProjectName: "kubeshop/testkube-operator",
		License:     mit,
		URLs: []string{
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/executor.testkube.io_executors.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/executor.testkube.io_webhooks.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/tests.testkube.io_scripts.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/tests.testkube.io_testexecutions.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/tests.testkube.io_tests.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/tests.testkube.io_testsources.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/tests.testkube.io_testsuiteexecutions.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/tests.testkube.io_testsuites.yaml",
			"https://github.com/kubeshop/testkube-operator/blob/develop/config/crd/bases/tests.testkube.io_testtriggers.yaml",
		},
	},
	{
		ProjectName: "kubevious/workload-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kubevious/workload-operator/blob/main/crds/workload-profile.yaml",
			"https://github.com/kubevious/workload-operator/blob/main/crds/workload.yaml",
		},
	},
	{
		ProjectName: "kumahq/kuma",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_circuitbreakers.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_containerpatches.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_dataplaneinsights.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_dataplanes.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_externalservices.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_faultinjections.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_healthchecks.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshaccesslogs.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshcircuitbreakers.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshes.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshfaultinjections.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshgatewayconfigs.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshgatewayinstances.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshgatewayroutes.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshgateways.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshhealthchecks.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshhttproutes.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshinsights.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshloadbalancingstrategies.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshproxypatches.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshratelimits.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshretries.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshtcproutes.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshtimeouts.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshtraces.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_meshtrafficpermissions.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_proxytemplates.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_ratelimits.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_retries.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_serviceinsights.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_timeouts.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_trafficlogs.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_trafficpermissions.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_trafficroutes.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_traffictraces.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_virtualoutbounds.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_zoneegresses.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_zoneegressinsights.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_zoneingresses.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_zoneingressinsights.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_zoneinsights.yaml",
			"https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/kuma.io_zones.yaml",
		},
	},
	{
		ProjectName: "kyverno/kyverno",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_admissionreports.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_backgroundscanreports.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_cleanuppolicies.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_clusteradmissionreports.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_clusterbackgroundscanreports.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_clustercleanuppolicies.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_clusterpolicies.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_policies.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_policyexceptions.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno.io_updaterequests.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/wgpolicyk8s.io_clusterpolicyreports.yaml",
			"https://github.com/kyverno/kyverno/blob/main/config/crds/wgpolicyk8s.io_policyreports.yaml",
		},
	},
	{
		ProjectName: "l7mp/stunner",
		License:     mit,
		URLs: []string{
			"https://github.com/l7mp/stunner/blob/main/deploy/manifests/static/stunner-crd.yaml",
		},
	},
	{
		ProjectName: "Lerentis/bitwarden-crd-operator",
		License:     mit,
		URLs: []string{
			"https://github.com/Lerentis/bitwarden-crd-operator/blob/main/charts/bitwarden-crd-operator/crds/bitwarden-secrets.yaml",
			"https://github.com/Lerentis/bitwarden-crd-operator/blob/main/charts/bitwarden-crd-operator/crds/bitwarden-templates.yaml",
			"https://github.com/Lerentis/bitwarden-crd-operator/blob/main/charts/bitwarden-crd-operator/crds/registry-credentials.yaml",
		},
	},
	{
		ProjectName: "lightbend/akka-cluster-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/lightbend/akka-cluster-operator/blob/master/deploy/crds/app_v1alpha1_akkacluster_crd.yaml",
		},
	},
	{
		ProjectName: "linki/cloudformation-operator",
		License:     mit,
		URLs: []string{
			"https://github.com/linki/cloudformation-operator/blob/master/config/crd/bases/cloudformation.linki.space_stacks.yaml",
		},
	},
	{
		ProjectName: "litmuschaos/chaos-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/litmuschaos/chaos-operator/blob/master/deploy/crds/chaosengine_crd.yaml",
			"https://github.com/litmuschaos/chaos-operator/blob/master/deploy/crds/chaosexperiment_crd.yaml",
			"https://github.com/litmuschaos/chaos-operator/blob/master/deploy/crds/chaosresults_crd.yaml",
		},
	},
	{
		ProjectName: "longhorn/longhorn",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml",
		},
	},
	{
		ProjectName: "lukaszraczylo/jobs-manager-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/lukaszraczylo/jobs-manager-operator/blob/main/config/crd/bases/jobsmanager.raczylo.com_managedjobs.yaml",
		},
	},
	{
		ProjectName: "m88i/nexus-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/m88i/nexus-operator/blob/main/config/crd/bases/apps.m88i.io_nexus.yaml",
		},
	},
	{
		ProjectName: "mariadb-operator/mariadb-operator",
		License:     mit,
		URLs: []string{
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_backups.yaml",
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_connections.yaml",
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_databases.yaml",
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_grants.yaml",
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_mariadbs.yaml",
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_restores.yaml",
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_sqljobs.yaml",
			"https://github.com/mariadb-operator/mariadb-operator/blob/main/config/crd/bases/mariadb.mmontes.io_users.yaml",
		},
	},
	{
		ProjectName: "mattermost/mattermost-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/mattermost/mattermost-operator/blob/master/config/crd/bases/installation.mattermost.com_mattermosts.yaml",
			"https://github.com/mattermost/mattermost-operator/blob/master/config/crd/bases/mattermost.com_clusterinstallations.yaml",
			"https://github.com/mattermost/mattermost-operator/blob/master/config/crd/bases/mattermost.com_mattermostrestoredbs.yaml",
		},
	},
	{
		ProjectName: "metacontroller/metacontroller",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/metacontroller/metacontroller/blob/master/manifests/production/metacontroller-crds-v1.yaml",
		},
	},
	{
		ProjectName: "metal3-io/baremetal-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/metal3-io/baremetal-operator/blob/main/config/crd/bases/metal3.io_baremetalhosts.yaml",
			"https://github.com/metal3-io/baremetal-operator/blob/main/config/crd/bases/metal3.io_bmceventsubscriptions.yaml",
			"https://github.com/metal3-io/baremetal-operator/blob/main/config/crd/bases/metal3.io_firmwareschemas.yaml",
			"https://github.com/metal3-io/baremetal-operator/blob/main/config/crd/bases/metal3.io_hardwaredata.yaml",
			"https://github.com/metal3-io/baremetal-operator/blob/main/config/crd/bases/metal3.io_hostfirmwaresettings.yaml",
			"https://github.com/metal3-io/baremetal-operator/blob/main/config/crd/bases/metal3.io_preprovisioningimages.yaml",
		},
	},
	{
		ProjectName: "microcks/microcks-ansible-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/microcks/microcks-ansible-operator/blob/master/deploy/crds/microcks_v1alpha1_microcksinstall_crd.yaml",
		},
	},
	{
		ProjectName: "minio/operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/minio/operator/blob/master/resources/base/crds/minio.min.io_tenants.yaml",
		},
	},
	{
		ProjectName: "mittwald/kubernetes-secret-generator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/mittwald/kubernetes-secret-generator/blob/master/deploy/crds/secretgenerator.mittwald.de_basicauths_crd.yaml",
			"https://github.com/mittwald/kubernetes-secret-generator/blob/master/deploy/crds/secretgenerator.mittwald.de_sshkeypairs_crd.yaml",
			"https://github.com/mittwald/kubernetes-secret-generator/blob/master/deploy/crds/secretgenerator.mittwald.de_stringsecrets_crd.yaml",
		},
	},
	{
		ProjectName: "nginxinc/nginx-kubernetes-gateway",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/nginxinc/nginx-kubernetes-gateway/blob/main/deploy/manifests/crds/gateway.nginx.org_nginxgateways.yaml",
		},
	},
	{
		ProjectName: "opdev/synapse-helm",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/opdev/synapse-helm/blob/master/config/crd/bases/charts.opdev.io_synapses.yaml",
		},
	},
	{
		ProjectName: "open-cluster-management-io/registration-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/open-cluster-management-io/registration-operator/blob/main/deploy/cluster-manager/config/crds/0000_01_operator.open-cluster-management.io_clustermanagers.crd.yaml",
			"https://github.com/open-cluster-management-io/registration-operator/blob/main/deploy/klusterlet/config/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml",
		},
	},
	{
		ProjectName: "open-feature/open-feature-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/open-feature/open-feature-operator/blob/main/config/crd/bases/core.openfeature.dev_featureflagconfigurations.yaml",
		},
	},
	{
		ProjectName: "open-policy-agent/gatekeeper",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/assign-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/assignimage-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/assignmetadata-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/config-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/constraintpodstatus-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/constrainttemplate-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/constrainttemplatepodstatus-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/expansiontemplate-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/expansiontemplatepodstatus-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/modifyset-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/mutatorpodstatus-customresourcedefinition.yaml",
			"https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/crds/provider-customresourcedefinition.yaml",
		},
	},
	{
		ProjectName: "open-telemetry/opentelemetry-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/open-telemetry/opentelemetry-operator/blob/main/config/crd/bases/opentelemetry.io_instrumentations.yaml",
			"https://github.com/open-telemetry/opentelemetry-operator/blob/main/config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml",
		},
	},
	{
		ProjectName: "openshift/hive",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_checkpoints.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterclaims.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterdeployments.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterdeprovisions.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterimagesets.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterpools.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterprovisions.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterrelocates.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_clusterstates.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hiveinternal.openshift.io_clustersyncleases.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_dnszones.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_hiveconfigs.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_machinepoolnameleases.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_machinepools.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_selectorsyncsets.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_syncidentityproviders.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hive.openshift.io_syncsets.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hiveinternal.openshift.io_clustersyncs.yaml",
			"https://github.com/openshift/hive/blob/master/config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml",
		},
	},
	{
		ProjectName: "otterize/helm-charts",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/otterize/helm-charts/blob/main/intents-operator/crds/clientintents-customresourcedefinition.yaml",
			"https://github.com/otterize/helm-charts/blob/main/intents-operator/crds/kafkaserverconfigs-customresourcedefinition.yaml",
			"https://github.com/otterize/helm-charts/blob/main/intents-operator/crds/protectedservices-customresourcedefinition.yaml",
		},
	},
	{
		ProjectName: "projectcalico/calico",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/projectcalico/calico/blob/master/manifests/crds.yaml",
			"https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/crds/operator.tigera.io_apiservers_crd.yaml",
			"https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml",
			"https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml",
			"https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/crds/operator.tigera.io_tigerastatuses_crd.yaml",
		},
	},
	{
		ProjectName: "prometheus-operator/prometheus-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml",
			"https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml",
		},
	},
	{
		ProjectName: "quay/container-security-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/quay/container-security-operator/blob/master/bundle/manifests/imagemanifestvulns.secscan.quay.redhat.com.crd.yaml",
		},
	},
	{
		ProjectName: "quay/quay-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/quay/quay-operator/blob/master/config/crd/bases/quay.redhat.com_quayregistries.yaml",
		},
	},
	{
		ProjectName: "redhat-cop/namespace-configuration-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/redhat-cop/namespace-configuration-operator/blob/master/config/crd/bases/redhatcop.redhat.io_groupconfigs.yaml",
			"https://github.com/redhat-cop/namespace-configuration-operator/blob/master/config/crd/bases/redhatcop.redhat.io_namespaceconfigs.yaml",
			"https://github.com/redhat-cop/namespace-configuration-operator/blob/master/config/crd/bases/redhatcop.redhat.io_userconfigs.yaml",
		},
	},
	{
		ProjectName: "redhat-developer/service-binding-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/redhat-developer/service-binding-operator/blob/master/config/crd/bases/binding.operators.coreos.com_bindablekinds.yaml",
			"https://github.com/redhat-developer/service-binding-operator/blob/master/config/crd/bases/binding.operators.coreos.com_servicebindings.yaml",
			"https://github.com/redhat-developer/service-binding-operator/blob/master/config/crd/bases/servicebinding.io_clusterworkloadresourcemappings.yaml",
			"https://github.com/redhat-developer/service-binding-operator/blob/master/config/crd/bases/servicebinding.io_servicebindings.yaml",
		},
	},
	{
		ProjectName: "redhat-performance/cluster-impairment-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/redhat-performance/cluster-impairment-operator/blob/main/config/crd/bases/apps.redhat.com_clusterimpairments.yaml",
		},
	},
	{
		ProjectName: "RedisLabs/redis-enterprise-k8s-docs",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/crds/reaadb_crd.yaml",
			"https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/crds/rec_crd.yaml",
			"https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/crds/redb_crd.yaml",
			"https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/crds/rerc_crd.yaml",
		},
	},
	{
		ProjectName: "rook/rook",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/rook/rook/blob/master/deploy/examples/crds.yaml",
		},
	},
	{
		ProjectName: "schemahero/schemahero",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/schemahero/schemahero/blob/main/config/crds/v1/databases.schemahero.io_databases.yaml",
			"https://github.com/schemahero/schemahero/blob/main/config/crds/v1/schemas.schemahero.io_datatypes.yaml",
			"https://github.com/schemahero/schemahero/blob/main/config/crds/v1/schemas.schemahero.io_migrations.yaml",
			"https://github.com/schemahero/schemahero/blob/main/config/crds/v1/schemas.schemahero.io_tables.yaml",
		},
	},
	{
		ProjectName: "scylladb/scylla-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/scylladb/scylla-operator/blob/master/pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml",
			"https://github.com/scylladb/scylla-operator/blob/master/pkg/api/scylla/v1alpha1/scylla.scylladb.com_nodeconfigs.yaml",
			"https://github.com/scylladb/scylla-operator/blob/master/pkg/api/scylla/v1alpha1/scylla.scylladb.com_scyllaoperatorconfigs.yaml",
		},
	},
	{
		ProjectName: "sematext/sematext-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/sematext/sematext-operator/blob/master/deploy/crds/sematext_v1_sematextagent_crd.yaml",
		},
	},
	{
		ProjectName: "sigstore/sigstore-helm-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/sigstore/sigstore-helm-operator/blob/main/config/crd/bases/helm.sigstore.dev_rekors.yaml",
		},
	},
	{
		ProjectName: "smartxworks/virtink",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/smartxworks/virtink/blob/main/deploy/crd/virt.virtink.smartx.com_virtualmachinemigrations.yaml",
			"https://github.com/smartxworks/virtink/blob/main/deploy/crd/virt.virtink.smartx.com_virtualmachines.yaml",
		},
	},
	{
		ProjectName: "snyk/kubernetes-monitor",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/snyk/kubernetes-monitor/blob/staging/snyk-operator/deploy/olm-catalog/snyk-operator/0.0.0/snykmonitors.charts.helm.k8s.io.crd.yaml",
		},
	},
	{
		ProjectName: "solo-io/gloo",
		License:     mit,
		URLs: []string{
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml",
			"https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/graphql.gloo.solo.io_v1beta1_GraphQLApi.yaml",
		},
	},
	{
		ProjectName: "strimzi/strimzi-kafka-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/040-Crd-kafka.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/041-Crd-kafkaconnect.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/042-Crd-strimzipodset.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/043-Crd-kafkatopic.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/044-Crd-kafkauser.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/045-Crd-kafkamirrormaker.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/046-Crd-kafkabridge.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/047-Crd-kafkaconnector.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/048-Crd-kafkamirrormaker2.yaml",
			"https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/049-Crd-kafkarebalance.yaml",
		},
	},
	{
		ProjectName: "superedge/superedge",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/superedge/superedge/blob/main/pkg/site-manager/crd/site.superedge.io_nodegroups.yaml",
			"https://github.com/superedge/superedge/blob/main/pkg/site-manager/crd/site.superedge.io_nodeunits.yaml",
		},
	},
	{
		ProjectName: "tektoncd/operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/tektoncd/operator/blob/main/config/base/300-operator_v1alpha1_chain_crd.yaml",
			"https://github.com/tektoncd/operator/blob/main/config/base/300-operator_v1alpha1_config_crd.yaml",
			"https://github.com/tektoncd/operator/blob/main/config/base/300-operator_v1alpha1_hub_crd.yaml",
			"https://github.com/tektoncd/operator/blob/main/config/base/300-operator_v1alpha1_installer_set_crd.yaml",
			"https://github.com/tektoncd/operator/blob/main/config/base/300-operator_v1alpha1_pipeline_crd.yaml",
			"https://github.com/tektoncd/operator/blob/main/config/base/300-operator_v1alpha1_trigger_crd.yaml",
		},
	},
	{
		ProjectName: "traefik/traefik",
		License:     mit,
		URLs: []string{
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_ingressroutes.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_ingressroutetcps.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_ingressrouteudps.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_middlewares.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_middlewaretcps.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_serverstransports.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_serverstransporttcps.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_tlsoptions.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_tlsstores.yaml",
			"https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/traefik.io_traefikservices.yaml",
		},
	},
	{
		ProjectName: "volcano-sh/volcano",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/volcano-sh/volcano/blob/master/config/crd/volcano/bases/batch.volcano.sh_jobs.yaml",
			"https://github.com/volcano-sh/volcano/blob/master/config/crd/volcano/bases/bus.volcano.sh_commands.yaml",
			"https://github.com/volcano-sh/volcano/blob/master/config/crd/volcano/bases/nodeinfo.volcano.sh_numatopologies.yaml",
			"https://github.com/volcano-sh/volcano/blob/master/config/crd/volcano/bases/scheduling.volcano.sh_podgroups.yaml",
			"https://github.com/volcano-sh/volcano/blob/master/config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml",
			"https://github.com/volcano-sh/volcano/blob/master/config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml",
			"https://github.com/volcano-sh/volcano/blob/master/config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml",
		},
	},
	{
		ProjectName: "wildfly/wildfly-operator",
		License:     apacheV2,
		URLs: []string{
			"https://github.com/wildfly/wildfly-operator/blob/main/config/crd/bases/wildfly.org_wildflyservers.yaml",
		},
	},
	{
		ProjectName: "zalando/postgres-operator",
		License:     mit,
		URLs: []string{
			"https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/crds/postgresqls.yaml",
			"https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/crds/operatorconfigurations.yaml",
			"https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/crds/postgresteams.yaml",
		},
	},
}
