/*
* SPDX-FileCopyrightText: The terraform-provider-k8s Authors
* SPDX-License-Identifier: 0BSD
 */

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/metio/terraform-provider-k8s/internal/provider/acid_zalan_do_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/acme_cert_manager_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/agent_k8s_elastic_co_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apicodegen_apimatic_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apiextensions_crossplane_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apiextensions_crossplane_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apigatewayv2_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apm_k8s_elastic_co_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apm_k8s_elastic_co_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/app_kiegroup_org_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/app_lightbend_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/app_redislabs_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/app_redislabs_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/applicationautoscaling_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_3scale_net_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_clusternet_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_gitlab_com_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_gitlab_com_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_kubedl_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_kubeedge_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_m88i_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/apps_redhat_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/aquasecurity_github_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/argoproj_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/argoproj_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/asdb_aerospike_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/asdb_aerospike_com_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/autoscaling_k8s_elastic_co_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/autoscaling_k8s_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/autoscaling_k8s_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/autoscaling_karmada_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/batch_volcano_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/beat_k8s_elastic_co_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/binding_operators_coreos_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/bitnami_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/bus_volcano_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/cache_kubedl_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/caching_ibm_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/camel_apache_org_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/camel_apache_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/capsule_clastix_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/capsule_clastix_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/capsule_clastix_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/ceph_rook_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/cert_manager_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/chaos_mesh_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/charts_flagsmith_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/charts_helm_k8s_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/charts_opdev_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/charts_operatorhub_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/che_eclipse_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/cilium_io_v2"
	"github.com/metio/terraform-provider-k8s/internal/provider/cilium_io_v2alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/cloudformation_linki_space_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/cluster_clusterpedia_io_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/clusters_clusternet_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/config_gatekeeper_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/config_grafana_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/config_karmada_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/config_koordinator_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/core_openfeature_dev_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/core_openfeature_dev_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/core_strimzi_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/couchbase_com_v2"
	"github.com/metio/terraform-provider-k8s/internal/provider/crd_projectcalico_org_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/data_fluid_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/databases_schemahero_io_v1alpha4"
	"github.com/metio/terraform-provider-k8s/internal/provider/devices_kubeedge_io_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/digitalis_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/digitalis_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/dynamodb_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/ec2_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/ecr_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/eks_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/elasticache_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/elasticsearch_k8s_elastic_co_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/elasticsearch_k8s_elastic_co_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/elbv2_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/elbv2_k8s_aws_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/emrcontainers_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/enterprise_gloo_solo_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/enterprisesearch_k8s_elastic_co_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/enterprisesearch_k8s_elastic_co_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/execution_furiko_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/executor_testkube_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/expansion_gatekeeper_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/expansion_gatekeeper_sh_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/extensions_istio_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/external_secrets_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/external_secrets_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/externaldata_gatekeeper_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/externaldata_gatekeeper_sh_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/externaldns_k8s_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/flagger_app_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/flink_apache_org_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/flow_volcano_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/fossul_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/gateway_networking_k8s_io_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/gateway_nginx_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/gateway_solo_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/getambassador_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/getambassador_io_v2"
	"github.com/metio/terraform-provider-k8s/internal/provider/getambassador_io_v3alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/gloo_solo_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/grafana_integreatly_org_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/graphql_gloo_solo_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/hazelcast_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/helm_sigstore_dev_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/helm_toolkit_fluxcd_io_v2beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/hive_openshift_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/hiveinternal_openshift_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/hyperfoil_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/hyperfoil_io_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/iam_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/ibmcloud_ibm_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/image_toolkit_fluxcd_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/image_toolkit_fluxcd_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/imaging_ingestion_alvearie_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/inference_kubedl_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/infinispan_org_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/infinispan_org_v2alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/installation_mattermost_com_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/iot_eclipse_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/jaegertracing_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/jobsmanager_raczylo_com_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/k8gb_absa_oss_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/k8s_otterize_com_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/kafka_strimzi_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kafka_strimzi_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kafka_strimzi_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/keda_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/keycloak_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kiali_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kibana_k8s_elastic_co_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kibana_k8s_elastic_co_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kms_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kubevious_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kuma_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kustomize_toolkit_fluxcd_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kustomize_toolkit_fluxcd_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kustomize_toolkit_fluxcd_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/kyverno_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kyverno_io_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/kyverno_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kyverno_io_v2alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/kyverno_io_v2beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/lambda_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/lb_lbconfig_carlosedp_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/lerentis_uploadfilter24_eu_v1beta4"
	"github.com/metio/terraform-provider-k8s/internal/provider/litmuschaos_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/logging_banzaicloud_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/logging_banzaicloud_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/logging_extensions_banzaicloud_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/loki_grafana_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/loki_grafana_com_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/longhorn_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/longhorn_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/maps_k8s_elastic_co_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/mariadb_mmontes_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/mattermost_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/metacontroller_k8s_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/metal3_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/minio_min_io_v2"
	"github.com/metio/terraform-provider-k8s/internal/provider/mirrors_kts_studio_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/mirrors_kts_studio_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/model_kubedl_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/monitoring_coreos_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/monitoring_coreos_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/mq_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/multicluster_x_k8s_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/mutations_gatekeeper_sh_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/mutations_gatekeeper_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/mutations_gatekeeper_sh_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/networking_istio_io_v1alpha3"
	"github.com/metio/terraform-provider-k8s/internal/provider/networking_istio_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/networking_karmada_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/nfd_k8s_sigs_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/nodeinfo_volcano_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/notebook_kubedl_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/notification_toolkit_fluxcd_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/notification_toolkit_fluxcd_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/notification_toolkit_fluxcd_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/objectbucket_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/opensearchservice_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/opentelemetry_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/operations_kubeedge_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/operator_aquasec_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/operator_cryostat_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/operator_knative_dev_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/operator_open_cluster_management_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/operator_tigera_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/org_eclipse_che_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/org_eclipse_che_v2"
	"github.com/metio/terraform-provider-k8s/internal/provider/pkg_crossplane_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/pkg_crossplane_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/pkg_crossplane_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/policy_clusterpedia_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/policy_karmada_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/postgres_operator_crunchydata_com_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/prometheusservice_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/quay_redhat_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/rds_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/redhatcop_redhat_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/registry_apicur_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/reliablesyncs_kubeedge_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/resources_teleport_dev_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/resources_teleport_dev_v2"
	"github.com/metio/terraform-provider-k8s/internal/provider/resources_teleport_dev_v3"
	"github.com/metio/terraform-provider-k8s/internal/provider/resources_teleport_dev_v5"
	"github.com/metio/terraform-provider-k8s/internal/provider/resources_teleport_dev_v6"
	"github.com/metio/terraform-provider-k8s/internal/provider/ripsaw_cloudbulldozer_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/rocketmq_apache_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/rules_kubeedge_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/s3_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/sagemaker_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/scheduling_koordinator_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/scheduling_sigs_k8s_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/scheduling_volcano_sh_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/schemas_schemahero_io_v1alpha4"
	"github.com/metio/terraform-provider-k8s/internal/provider/scylla_scylladb_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/scylla_scylladb_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/secretgenerator_mittwald_de_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/secrets_crossplane_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/secscan_quay_redhat_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/security_istio_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/security_istio_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/security_profiles_operator_x_k8s_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/security_profiles_operator_x_k8s_io_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/security_profiles_operator_x_k8s_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/sematext_com_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/servicebinding_io_v1alpha3"
	"github.com/metio/terraform-provider-k8s/internal/provider/servicebinding_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/serving_kubedl_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/sfn_services_k8s_aws_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/site_superedge_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/slo_koordinator_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/source_toolkit_fluxcd_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/source_toolkit_fluxcd_io_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/source_toolkit_fluxcd_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/sparkoperator_k8s_io_v1beta2"
	"github.com/metio/terraform-provider-k8s/internal/provider/stunner_l7mp_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/telemetry_istio_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/templates_gatekeeper_sh_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/templates_gatekeeper_sh_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/templates_gatekeeper_sh_v1beta1"
	"github.com/metio/terraform-provider-k8s/internal/provider/tests_testkube_io_v1"
	"github.com/metio/terraform-provider-k8s/internal/provider/tests_testkube_io_v2"
	"github.com/metio/terraform-provider-k8s/internal/provider/tests_testkube_io_v3"
	"github.com/metio/terraform-provider-k8s/internal/provider/topology_node_k8s_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/traefik_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/training_kubedl_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/virt_virtink_smartx_com_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/wgpolicyk8s_io_v1alpha2"
	"github.com/metio/terraform-provider-k8s/internal/provider/wildfly_org_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/work_karmada_io_v1alpha1"
	"github.com/metio/terraform-provider-k8s/internal/provider/work_karmada_io_v1alpha2"
)

func allResources() []func() resource.Resource {
	return []func() resource.Resource{
		acid_zalan_do_v1.NewAcidZalanDoOperatorConfigurationV1Resource,
		acid_zalan_do_v1.NewAcidZalanDoPostgresTeamV1Resource,
		acid_zalan_do_v1.NewAcidZalanDoPostgresqlV1Resource,
		acme_cert_manager_io_v1.NewAcmeCertManagerIoChallengeV1Resource,
		acme_cert_manager_io_v1.NewAcmeCertManagerIoOrderV1Resource,
		agent_k8s_elastic_co_v1alpha1.NewAgentK8SElasticCoAgentV1Alpha1Resource,
		apicodegen_apimatic_io_v1beta1.NewApicodegenApimaticIoAPIMaticV1Beta1Resource,
		apiextensions_crossplane_io_v1.NewApiextensionsCrossplaneIoCompositeResourceDefinitionV1Resource,
		apiextensions_crossplane_io_v1.NewApiextensionsCrossplaneIoCompositionRevisionV1Resource,
		apiextensions_crossplane_io_v1.NewApiextensionsCrossplaneIoCompositionV1Resource,
		apiextensions_crossplane_io_v1beta1.NewApiextensionsCrossplaneIoCompositionRevisionV1Beta1Resource,
		apigatewayv2_services_k8s_aws_v1alpha1.NewApigatewayv2ServicesK8SAwsAPIV1Alpha1Resource,
		apigatewayv2_services_k8s_aws_v1alpha1.NewApigatewayv2ServicesK8SAwsAuthorizerV1Alpha1Resource,
		apigatewayv2_services_k8s_aws_v1alpha1.NewApigatewayv2ServicesK8SAwsDeploymentV1Alpha1Resource,
		apigatewayv2_services_k8s_aws_v1alpha1.NewApigatewayv2ServicesK8SAwsIntegrationV1Alpha1Resource,
		apigatewayv2_services_k8s_aws_v1alpha1.NewApigatewayv2ServicesK8SAwsRouteV1Alpha1Resource,
		apigatewayv2_services_k8s_aws_v1alpha1.NewApigatewayv2ServicesK8SAwsStageV1Alpha1Resource,
		apigatewayv2_services_k8s_aws_v1alpha1.NewApigatewayv2ServicesK8SAwsVPCLinkV1Alpha1Resource,
		apm_k8s_elastic_co_v1.NewApmK8SElasticCoApmServerV1Resource,
		apm_k8s_elastic_co_v1beta1.NewApmK8SElasticCoApmServerV1Beta1Resource,
		app_kiegroup_org_v1beta1.NewAppKiegroupOrgKogitoBuildV1Beta1Resource,
		app_kiegroup_org_v1beta1.NewAppKiegroupOrgKogitoInfraV1Beta1Resource,
		app_kiegroup_org_v1beta1.NewAppKiegroupOrgKogitoRuntimeV1Beta1Resource,
		app_kiegroup_org_v1beta1.NewAppKiegroupOrgKogitoSupportingServiceV1Beta1Resource,
		app_lightbend_com_v1alpha1.NewAppLightbendComAkkaClusterV1Alpha1Resource,
		app_redislabs_com_v1.NewAppRedislabsComRedisEnterpriseClusterV1Resource,
		app_redislabs_com_v1alpha1.NewAppRedislabsComRedisEnterpriseActiveActiveDatabaseV1Alpha1Resource,
		app_redislabs_com_v1alpha1.NewAppRedislabsComRedisEnterpriseClusterV1Alpha1Resource,
		app_redislabs_com_v1alpha1.NewAppRedislabsComRedisEnterpriseDatabaseV1Alpha1Resource,
		app_redislabs_com_v1alpha1.NewAppRedislabsComRedisEnterpriseRemoteClusterV1Alpha1Resource,
		applicationautoscaling_services_k8s_aws_v1alpha1.NewApplicationautoscalingServicesK8SAwsScalableTargetV1Alpha1Resource,
		applicationautoscaling_services_k8s_aws_v1alpha1.NewApplicationautoscalingServicesK8SAwsScalingPolicyV1Alpha1Resource,
		apps_3scale_net_v1alpha1.NewApps3ScaleNetAPIcastV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoBaseV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoDescriptionV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoFeedInventoryV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoGlobalizationV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoHelmChartV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoHelmReleaseV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoLocalizationV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoManifestV1Alpha1Resource,
		apps_clusternet_io_v1alpha1.NewAppsClusternetIoSubscriptionV1Alpha1Resource,
		apps_gitlab_com_v1beta1.NewAppsGitlabComGitLabV1Beta1Resource,
		apps_gitlab_com_v1beta2.NewAppsGitlabComRunnerV1Beta2Resource,
		apps_kubedl_io_v1alpha1.NewAppsKubedlIoCronV1Alpha1Resource,
		apps_kubeedge_io_v1alpha1.NewAppsKubeedgeIoEdgeApplicationV1Alpha1Resource,
		apps_kubeedge_io_v1alpha1.NewAppsKubeedgeIoNodeGroupV1Alpha1Resource,
		apps_m88i_io_v1alpha1.NewAppsM88IIoNexusV1Alpha1Resource,
		apps_redhat_com_v1alpha1.NewAppsRedhatComClusterImpairmentV1Alpha1Resource,
		aquasecurity_github_io_v1alpha1.NewAquasecurityGithubIoAquaStarboardV1Alpha1Resource,
		argoproj_io_v1alpha1.NewArgoprojIoAppProjectV1Alpha1Resource,
		argoproj_io_v1alpha1.NewArgoprojIoApplicationSetV1Alpha1Resource,
		argoproj_io_v1alpha1.NewArgoprojIoApplicationV1Alpha1Resource,
		argoproj_io_v1alpha1.NewArgoprojIoArgoCDExportV1Alpha1Resource,
		argoproj_io_v1alpha1.NewArgoprojIoArgoCDV1Alpha1Resource,
		argoproj_io_v1beta1.NewArgoprojIoArgoCDV1Beta1Resource,
		asdb_aerospike_com_v1.NewAsdbAerospikeComAerospikeClusterV1Resource,
		asdb_aerospike_com_v1beta1.NewAsdbAerospikeComAerospikeClusterV1Beta1Resource,
		autoscaling_k8s_elastic_co_v1alpha1.NewAutoscalingK8SElasticCoElasticsearchAutoscalerV1Alpha1Resource,
		autoscaling_k8s_io_v1.NewAutoscalingK8SIoVerticalPodAutoscalerCheckpointV1Resource,
		autoscaling_k8s_io_v1.NewAutoscalingK8SIoVerticalPodAutoscalerV1Resource,
		autoscaling_k8s_io_v1beta2.NewAutoscalingK8SIoVerticalPodAutoscalerCheckpointV1Beta2Resource,
		autoscaling_k8s_io_v1beta2.NewAutoscalingK8SIoVerticalPodAutoscalerV1Beta2Resource,
		autoscaling_karmada_io_v1alpha1.NewAutoscalingKarmadaIoCronFederatedHPAV1Alpha1Resource,
		autoscaling_karmada_io_v1alpha1.NewAutoscalingKarmadaIoFederatedHPAV1Alpha1Resource,
		batch_volcano_sh_v1alpha1.NewBatchVolcanoShJobV1Alpha1Resource,
		beat_k8s_elastic_co_v1beta1.NewBeatK8SElasticCoBeatV1Beta1Resource,
		binding_operators_coreos_com_v1alpha1.NewBindingOperatorsCoreosComServiceBindingV1Alpha1Resource,
		bitnami_com_v1alpha1.NewBitnamiComSealedSecretV1Alpha1Resource,
		bus_volcano_sh_v1alpha1.NewBusVolcanoShCommandV1Alpha1Resource,
		cache_kubedl_io_v1alpha1.NewCacheKubedlIoCacheBackendV1Alpha1Resource,
		caching_ibm_com_v1alpha1.NewCachingIbmComVarnishClusterV1Alpha1Resource,
		camel_apache_org_v1.NewCamelApacheOrgBuildV1Resource,
		camel_apache_org_v1.NewCamelApacheOrgCamelCatalogV1Resource,
		camel_apache_org_v1.NewCamelApacheOrgIntegrationKitV1Resource,
		camel_apache_org_v1.NewCamelApacheOrgIntegrationPlatformV1Resource,
		camel_apache_org_v1.NewCamelApacheOrgIntegrationV1Resource,
		camel_apache_org_v1.NewCamelApacheOrgKameletV1Resource,
		camel_apache_org_v1alpha1.NewCamelApacheOrgKameletBindingV1Alpha1Resource,
		camel_apache_org_v1alpha1.NewCamelApacheOrgKameletV1Alpha1Resource,
		capsule_clastix_io_v1alpha1.NewCapsuleClastixIoCapsuleConfigurationV1Alpha1Resource,
		capsule_clastix_io_v1alpha1.NewCapsuleClastixIoTenantV1Alpha1Resource,
		capsule_clastix_io_v1beta1.NewCapsuleClastixIoTenantV1Beta1Resource,
		capsule_clastix_io_v1beta2.NewCapsuleClastixIoCapsuleConfigurationV1Beta2Resource,
		capsule_clastix_io_v1beta2.NewCapsuleClastixIoTenantV1Beta2Resource,
		ceph_rook_io_v1.NewCephRookIoCephBlockPoolRadosNamespaceV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephBlockPoolV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephBucketNotificationV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephBucketTopicV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephCOSIDriverV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephClientV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephClusterV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephFilesystemMirrorV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephFilesystemSubVolumeGroupV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephFilesystemV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephNFSV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephObjectRealmV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephObjectStoreUserV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephObjectStoreV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephObjectZoneGroupV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephObjectZoneV1Resource,
		ceph_rook_io_v1.NewCephRookIoCephRBDMirrorV1Resource,
		cert_manager_io_v1.NewCertManagerIoCertificateRequestV1Resource,
		cert_manager_io_v1.NewCertManagerIoCertificateV1Resource,
		cert_manager_io_v1.NewCertManagerIoClusterIssuerV1Resource,
		cert_manager_io_v1.NewCertManagerIoIssuerV1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgAWSChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgAzureChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgBlockChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgDNSChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgGCPChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgHTTPChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgIOChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgJVMChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgKernelChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgNetworkChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgPhysicalMachineChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgPhysicalMachineV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgPodChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgPodHttpChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgPodIOChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgPodNetworkChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgRemoteClusterV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgScheduleV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgStatusCheckV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgStressChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgTimeChaosV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgWorkflowNodeV1Alpha1Resource,
		chaos_mesh_org_v1alpha1.NewChaosMeshOrgWorkflowV1Alpha1Resource,
		charts_flagsmith_com_v1alpha1.NewChartsFlagsmithComFlagsmithV1Alpha1Resource,
		charts_helm_k8s_io_v1alpha1.NewChartsHelmK8SIoSnykMonitorV1Alpha1Resource,
		charts_opdev_io_v1alpha1.NewChartsOpdevIoSynapseV1Alpha1Resource,
		charts_operatorhub_io_v1alpha1.NewChartsOperatorhubIoCockroachdbV1Alpha1Resource,
		che_eclipse_org_v1alpha1.NewCheEclipseOrgKubernetesImagePullerV1Alpha1Resource,
		cilium_io_v2.NewCiliumIoCiliumClusterwideEnvoyConfigV2Resource,
		cilium_io_v2.NewCiliumIoCiliumClusterwideNetworkPolicyV2Resource,
		cilium_io_v2.NewCiliumIoCiliumEgressGatewayPolicyV2Resource,
		cilium_io_v2.NewCiliumIoCiliumEnvoyConfigV2Resource,
		cilium_io_v2.NewCiliumIoCiliumExternalWorkloadV2Resource,
		cilium_io_v2.NewCiliumIoCiliumIdentityV2Resource,
		cilium_io_v2.NewCiliumIoCiliumLocalRedirectPolicyV2Resource,
		cilium_io_v2.NewCiliumIoCiliumNetworkPolicyV2Resource,
		cilium_io_v2.NewCiliumIoCiliumNodeV2Resource,
		cilium_io_v2alpha1.NewCiliumIoCiliumBGPPeeringPolicyV2Alpha1Resource,
		cilium_io_v2alpha1.NewCiliumIoCiliumCIDRGroupV2Alpha1Resource,
		cilium_io_v2alpha1.NewCiliumIoCiliumEndpointSliceV2Alpha1Resource,
		cilium_io_v2alpha1.NewCiliumIoCiliumL2AnnouncementPolicyV2Alpha1Resource,
		cilium_io_v2alpha1.NewCiliumIoCiliumLoadBalancerIPPoolV2Alpha1Resource,
		cilium_io_v2alpha1.NewCiliumIoCiliumNodeConfigV2Alpha1Resource,
		cilium_io_v2alpha1.NewCiliumIoCiliumPodIPPoolV2Alpha1Resource,
		cloudformation_linki_space_v1alpha1.NewCloudformationLinkiSpaceStackV1Alpha1Resource,
		cluster_clusterpedia_io_v1alpha2.NewClusterClusterpediaIoClusterSyncResourcesV1Alpha2Resource,
		cluster_clusterpedia_io_v1alpha2.NewClusterClusterpediaIoPediaClusterV1Alpha2Resource,
		clusters_clusternet_io_v1beta1.NewClustersClusternetIoClusterRegistrationRequestV1Beta1Resource,
		clusters_clusternet_io_v1beta1.NewClustersClusternetIoManagedClusterV1Beta1Resource,
		config_gatekeeper_sh_v1alpha1.NewConfigGatekeeperShConfigV1Alpha1Resource,
		config_grafana_com_v1.NewConfigGrafanaComProjectConfigV1Resource,
		config_karmada_io_v1alpha1.NewConfigKarmadaIoResourceInterpreterCustomizationV1Alpha1Resource,
		config_karmada_io_v1alpha1.NewConfigKarmadaIoResourceInterpreterWebhookConfigurationV1Alpha1Resource,
		config_koordinator_sh_v1alpha1.NewConfigKoordinatorShClusterColocationProfileV1Alpha1Resource,
		core_openfeature_dev_v1alpha1.NewCoreOpenfeatureDevFeatureFlagConfigurationV1Alpha1Resource,
		core_openfeature_dev_v1alpha2.NewCoreOpenfeatureDevFeatureFlagConfigurationV1Alpha2Resource,
		core_strimzi_io_v1beta2.NewCoreStrimziIoStrimziPodSetV1Beta2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseAutoscalerV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseBackupRestoreV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseBackupV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseBucketV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseClusterV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseCollectionGroupV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseCollectionV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseEphemeralBucketV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseGroupV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseMemcachedBucketV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseMigrationReplicationV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseReplicationV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseRoleBindingV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseScopeGroupV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseScopeV2Resource,
		couchbase_com_v2.NewCouchbaseComCouchbaseUserV2Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgBGPConfigurationV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgBGPFilterV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgBGPPeerV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgBlockAffinityV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgCalicoNodeStatusV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgClusterInformationV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgFelixConfigurationV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgGlobalNetworkPolicyV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgGlobalNetworkSetV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgHostEndpointV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgIPAMBlockV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgIPAMConfigV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgIPAMHandleV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgIPPoolV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgIPReservationV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgKubeControllersConfigurationV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgNetworkPolicyV1Resource,
		crd_projectcalico_org_v1.NewCrdProjectcalicoOrgNetworkSetV1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoAlluxioRuntimeV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoDataBackupV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoDataLoadV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoDatasetV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoGooseFSRuntimeV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoJindoRuntimeV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoJuiceFSRuntimeV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoThinRuntimeProfileV1Alpha1Resource,
		data_fluid_io_v1alpha1.NewDataFluidIoThinRuntimeV1Alpha1Resource,
		databases_schemahero_io_v1alpha4.NewDatabasesSchemaheroIoDatabaseV1Alpha4Resource,
		devices_kubeedge_io_v1alpha2.NewDevicesKubeedgeIoDeviceModelV1Alpha2Resource,
		devices_kubeedge_io_v1alpha2.NewDevicesKubeedgeIoDeviceV1Alpha2Resource,
		digitalis_io_v1.NewDigitalisIoValsSecretV1Resource,
		digitalis_io_v1beta1.NewDigitalisIoDbSecretV1Beta1Resource,
		dynamodb_services_k8s_aws_v1alpha1.NewDynamodbServicesK8SAwsBackupV1Alpha1Resource,
		dynamodb_services_k8s_aws_v1alpha1.NewDynamodbServicesK8SAwsGlobalTableV1Alpha1Resource,
		dynamodb_services_k8s_aws_v1alpha1.NewDynamodbServicesK8SAwsTableV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsDHCPOptionsV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsElasticIPAddressV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsInstanceV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsInternetGatewayV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsNATGatewayV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsRouteTableV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsSecurityGroupV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsSubnetV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsTransitGatewayV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsVPCEndpointV1Alpha1Resource,
		ec2_services_k8s_aws_v1alpha1.NewEc2ServicesK8SAwsVPCV1Alpha1Resource,
		ecr_services_k8s_aws_v1alpha1.NewEcrServicesK8SAwsPullThroughCacheRuleV1Alpha1Resource,
		ecr_services_k8s_aws_v1alpha1.NewEcrServicesK8SAwsRepositoryV1Alpha1Resource,
		eks_services_k8s_aws_v1alpha1.NewEksServicesK8SAwsAddonV1Alpha1Resource,
		eks_services_k8s_aws_v1alpha1.NewEksServicesK8SAwsClusterV1Alpha1Resource,
		eks_services_k8s_aws_v1alpha1.NewEksServicesK8SAwsFargateProfileV1Alpha1Resource,
		eks_services_k8s_aws_v1alpha1.NewEksServicesK8SAwsNodegroupV1Alpha1Resource,
		elasticache_services_k8s_aws_v1alpha1.NewElasticacheServicesK8SAwsCacheParameterGroupV1Alpha1Resource,
		elasticache_services_k8s_aws_v1alpha1.NewElasticacheServicesK8SAwsCacheSubnetGroupV1Alpha1Resource,
		elasticache_services_k8s_aws_v1alpha1.NewElasticacheServicesK8SAwsReplicationGroupV1Alpha1Resource,
		elasticache_services_k8s_aws_v1alpha1.NewElasticacheServicesK8SAwsSnapshotV1Alpha1Resource,
		elasticache_services_k8s_aws_v1alpha1.NewElasticacheServicesK8SAwsUserGroupV1Alpha1Resource,
		elasticache_services_k8s_aws_v1alpha1.NewElasticacheServicesK8SAwsUserV1Alpha1Resource,
		elasticsearch_k8s_elastic_co_v1.NewElasticsearchK8SElasticCoElasticsearchV1Resource,
		elasticsearch_k8s_elastic_co_v1beta1.NewElasticsearchK8SElasticCoElasticsearchV1Beta1Resource,
		elbv2_k8s_aws_v1alpha1.NewElbv2K8SAwsTargetGroupBindingV1Alpha1Resource,
		elbv2_k8s_aws_v1beta1.NewElbv2K8SAwsIngressClassParamsV1Beta1Resource,
		elbv2_k8s_aws_v1beta1.NewElbv2K8SAwsTargetGroupBindingV1Beta1Resource,
		emrcontainers_services_k8s_aws_v1alpha1.NewEmrcontainersServicesK8SAwsJobRunV1Alpha1Resource,
		emrcontainers_services_k8s_aws_v1alpha1.NewEmrcontainersServicesK8SAwsVirtualClusterV1Alpha1Resource,
		enterprise_gloo_solo_io_v1.NewEnterpriseGlooSoloIoAuthConfigV1Resource,
		enterprisesearch_k8s_elastic_co_v1.NewEnterprisesearchK8SElasticCoEnterpriseSearchV1Resource,
		enterprisesearch_k8s_elastic_co_v1beta1.NewEnterprisesearchK8SElasticCoEnterpriseSearchV1Beta1Resource,
		execution_furiko_io_v1alpha1.NewExecutionFurikoIoJobConfigV1Alpha1Resource,
		execution_furiko_io_v1alpha1.NewExecutionFurikoIoJobV1Alpha1Resource,
		executor_testkube_io_v1.NewExecutorTestkubeIoExecutorV1Resource,
		executor_testkube_io_v1.NewExecutorTestkubeIoWebhookV1Resource,
		expansion_gatekeeper_sh_v1alpha1.NewExpansionGatekeeperShExpansionTemplateV1Alpha1Resource,
		expansion_gatekeeper_sh_v1beta1.NewExpansionGatekeeperShExpansionTemplateV1Beta1Resource,
		extensions_istio_io_v1alpha1.NewExtensionsIstioIoWasmPluginV1Alpha1Resource,
		external_secrets_io_v1alpha1.NewExternalSecretsIoClusterSecretStoreV1Alpha1Resource,
		external_secrets_io_v1alpha1.NewExternalSecretsIoExternalSecretV1Alpha1Resource,
		external_secrets_io_v1alpha1.NewExternalSecretsIoSecretStoreV1Alpha1Resource,
		external_secrets_io_v1beta1.NewExternalSecretsIoClusterExternalSecretV1Beta1Resource,
		external_secrets_io_v1beta1.NewExternalSecretsIoClusterSecretStoreV1Beta1Resource,
		external_secrets_io_v1beta1.NewExternalSecretsIoExternalSecretV1Beta1Resource,
		external_secrets_io_v1beta1.NewExternalSecretsIoSecretStoreV1Beta1Resource,
		externaldata_gatekeeper_sh_v1alpha1.NewExternaldataGatekeeperShProviderV1Alpha1Resource,
		externaldata_gatekeeper_sh_v1beta1.NewExternaldataGatekeeperShProviderV1Beta1Resource,
		externaldns_k8s_io_v1alpha1.NewExternaldnsK8SIoDNSEndpointV1Alpha1Resource,
		flagger_app_v1beta1.NewFlaggerAppAlertProviderV1Beta1Resource,
		flagger_app_v1beta1.NewFlaggerAppCanaryV1Beta1Resource,
		flagger_app_v1beta1.NewFlaggerAppMetricTemplateV1Beta1Resource,
		flink_apache_org_v1beta1.NewFlinkApacheOrgFlinkDeploymentV1Beta1Resource,
		flink_apache_org_v1beta1.NewFlinkApacheOrgFlinkSessionJobV1Beta1Resource,
		flow_volcano_sh_v1alpha1.NewFlowVolcanoShJobFlowV1Alpha1Resource,
		flow_volcano_sh_v1alpha1.NewFlowVolcanoShJobTemplateV1Alpha1Resource,
		fossul_io_v1.NewFossulIoBackupConfigV1Resource,
		fossul_io_v1.NewFossulIoBackupScheduleV1Resource,
		fossul_io_v1.NewFossulIoBackupV1Resource,
		fossul_io_v1.NewFossulIoFossulV1Resource,
		fossul_io_v1.NewFossulIoRestoreV1Resource,
		gateway_networking_k8s_io_v1alpha2.NewGatewayNetworkingK8SIoGatewayClassV1Alpha2Resource,
		gateway_networking_k8s_io_v1alpha2.NewGatewayNetworkingK8SIoGatewayV1Alpha2Resource,
		gateway_networking_k8s_io_v1alpha2.NewGatewayNetworkingK8SIoHTTPRouteV1Alpha2Resource,
		gateway_networking_k8s_io_v1alpha2.NewGatewayNetworkingK8SIoTCPRouteV1Alpha2Resource,
		gateway_networking_k8s_io_v1alpha2.NewGatewayNetworkingK8SIoTLSRouteV1Alpha2Resource,
		gateway_nginx_org_v1alpha1.NewGatewayNginxOrgNginxGatewayV1Alpha1Resource,
		gateway_solo_io_v1.NewGatewaySoloIoGatewayV1Resource,
		gateway_solo_io_v1.NewGatewaySoloIoMatchableHttpGatewayV1Resource,
		gateway_solo_io_v1.NewGatewaySoloIoRouteOptionV1Resource,
		gateway_solo_io_v1.NewGatewaySoloIoRouteTableV1Resource,
		gateway_solo_io_v1.NewGatewaySoloIoVirtualHostOptionV1Resource,
		gateway_solo_io_v1.NewGatewaySoloIoVirtualServiceV1Resource,
		getambassador_io_v1.NewGetambassadorIoAuthServiceV1Resource,
		getambassador_io_v1.NewGetambassadorIoConsulResolverV1Resource,
		getambassador_io_v1.NewGetambassadorIoDevPortalV1Resource,
		getambassador_io_v1.NewGetambassadorIoKubernetesEndpointResolverV1Resource,
		getambassador_io_v1.NewGetambassadorIoKubernetesServiceResolverV1Resource,
		getambassador_io_v1.NewGetambassadorIoLogServiceV1Resource,
		getambassador_io_v1.NewGetambassadorIoMappingV1Resource,
		getambassador_io_v1.NewGetambassadorIoModuleV1Resource,
		getambassador_io_v1.NewGetambassadorIoRateLimitServiceV1Resource,
		getambassador_io_v1.NewGetambassadorIoTCPMappingV1Resource,
		getambassador_io_v1.NewGetambassadorIoTLSContextV1Resource,
		getambassador_io_v1.NewGetambassadorIoTracingServiceV1Resource,
		getambassador_io_v2.NewGetambassadorIoAuthServiceV2Resource,
		getambassador_io_v2.NewGetambassadorIoConsulResolverV2Resource,
		getambassador_io_v2.NewGetambassadorIoDevPortalV2Resource,
		getambassador_io_v2.NewGetambassadorIoHostV2Resource,
		getambassador_io_v2.NewGetambassadorIoKubernetesEndpointResolverV2Resource,
		getambassador_io_v2.NewGetambassadorIoKubernetesServiceResolverV2Resource,
		getambassador_io_v2.NewGetambassadorIoLogServiceV2Resource,
		getambassador_io_v2.NewGetambassadorIoMappingV2Resource,
		getambassador_io_v2.NewGetambassadorIoModuleV2Resource,
		getambassador_io_v2.NewGetambassadorIoRateLimitServiceV2Resource,
		getambassador_io_v2.NewGetambassadorIoTCPMappingV2Resource,
		getambassador_io_v2.NewGetambassadorIoTLSContextV2Resource,
		getambassador_io_v2.NewGetambassadorIoTracingServiceV2Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoAuthServiceV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoConsulResolverV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoDevPortalV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoHostV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoKubernetesEndpointResolverV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoKubernetesServiceResolverV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoListenerV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoLogServiceV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoMappingV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoModuleV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoRateLimitServiceV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoTCPMappingV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoTLSContextV3Alpha1Resource,
		getambassador_io_v3alpha1.NewGetambassadorIoTracingServiceV3Alpha1Resource,
		gloo_solo_io_v1.NewGlooSoloIoProxyV1Resource,
		gloo_solo_io_v1.NewGlooSoloIoSettingsV1Resource,
		gloo_solo_io_v1.NewGlooSoloIoUpstreamGroupV1Resource,
		gloo_solo_io_v1.NewGlooSoloIoUpstreamV1Resource,
		grafana_integreatly_org_v1beta1.NewGrafanaIntegreatlyOrgGrafanaDashboardV1Beta1Resource,
		grafana_integreatly_org_v1beta1.NewGrafanaIntegreatlyOrgGrafanaDatasourceV1Beta1Resource,
		grafana_integreatly_org_v1beta1.NewGrafanaIntegreatlyOrgGrafanaFolderV1Beta1Resource,
		grafana_integreatly_org_v1beta1.NewGrafanaIntegreatlyOrgGrafanaV1Beta1Resource,
		graphql_gloo_solo_io_v1beta1.NewGraphqlGlooSoloIoGraphQLApiV1Beta1Resource,
		hazelcast_com_v1alpha1.NewHazelcastComCronHotBackupV1Alpha1Resource,
		hazelcast_com_v1alpha1.NewHazelcastComHazelcastV1Alpha1Resource,
		hazelcast_com_v1alpha1.NewHazelcastComHotBackupV1Alpha1Resource,
		hazelcast_com_v1alpha1.NewHazelcastComManagementCenterV1Alpha1Resource,
		hazelcast_com_v1alpha1.NewHazelcastComMapV1Alpha1Resource,
		hazelcast_com_v1alpha1.NewHazelcastComWanReplicationV1Alpha1Resource,
		helm_sigstore_dev_v1alpha1.NewHelmSigstoreDevRekorV1Alpha1Resource,
		helm_toolkit_fluxcd_io_v2beta1.NewHelmToolkitFluxcdIoHelmReleaseV2Beta1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoCheckpointV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterClaimV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterDeploymentCustomizationV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterDeploymentV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterDeprovisionV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterImageSetV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterPoolV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterProvisionV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterRelocateV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoClusterStateV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoDNSZoneV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoHiveConfigV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoMachinePoolNameLeaseV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoMachinePoolV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoSelectorSyncIdentityProviderV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoSelectorSyncSetV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoSyncIdentityProviderV1Resource,
		hive_openshift_io_v1.NewHiveOpenshiftIoSyncSetV1Resource,
		hiveinternal_openshift_io_v1alpha1.NewHiveinternalOpenshiftIoClusterSyncLeaseV1Alpha1Resource,
		hiveinternal_openshift_io_v1alpha1.NewHiveinternalOpenshiftIoClusterSyncV1Alpha1Resource,
		hiveinternal_openshift_io_v1alpha1.NewHiveinternalOpenshiftIoFakeClusterInstallV1Alpha1Resource,
		hyperfoil_io_v1alpha1.NewHyperfoilIoHorreumV1Alpha1Resource,
		hyperfoil_io_v1alpha2.NewHyperfoilIoHyperfoilV1Alpha2Resource,
		iam_services_k8s_aws_v1alpha1.NewIamServicesK8SAwsGroupV1Alpha1Resource,
		iam_services_k8s_aws_v1alpha1.NewIamServicesK8SAwsPolicyV1Alpha1Resource,
		iam_services_k8s_aws_v1alpha1.NewIamServicesK8SAwsRoleV1Alpha1Resource,
		ibmcloud_ibm_com_v1alpha1.NewIbmcloudIbmComComposableV1Alpha1Resource,
		image_toolkit_fluxcd_io_v1beta1.NewImageToolkitFluxcdIoImagePolicyV1Beta1Resource,
		image_toolkit_fluxcd_io_v1beta1.NewImageToolkitFluxcdIoImageRepositoryV1Beta1Resource,
		image_toolkit_fluxcd_io_v1beta1.NewImageToolkitFluxcdIoImageUpdateAutomationV1Beta1Resource,
		image_toolkit_fluxcd_io_v1beta2.NewImageToolkitFluxcdIoImagePolicyV1Beta2Resource,
		image_toolkit_fluxcd_io_v1beta2.NewImageToolkitFluxcdIoImageRepositoryV1Beta2Resource,
		imaging_ingestion_alvearie_org_v1alpha1.NewImagingIngestionAlvearieOrgDicomEventBridgeV1Alpha1Resource,
		imaging_ingestion_alvearie_org_v1alpha1.NewImagingIngestionAlvearieOrgDicomEventDrivenIngestionV1Alpha1Resource,
		imaging_ingestion_alvearie_org_v1alpha1.NewImagingIngestionAlvearieOrgDicomInstanceBindingV1Alpha1Resource,
		imaging_ingestion_alvearie_org_v1alpha1.NewImagingIngestionAlvearieOrgDicomStudyBindingV1Alpha1Resource,
		imaging_ingestion_alvearie_org_v1alpha1.NewImagingIngestionAlvearieOrgDicomwebIngestionServiceV1Alpha1Resource,
		imaging_ingestion_alvearie_org_v1alpha1.NewImagingIngestionAlvearieOrgDimseIngestionServiceV1Alpha1Resource,
		imaging_ingestion_alvearie_org_v1alpha1.NewImagingIngestionAlvearieOrgDimseProxyV1Alpha1Resource,
		inference_kubedl_io_v1alpha1.NewInferenceKubedlIoElasticBatchJobV1Alpha1Resource,
		infinispan_org_v1.NewInfinispanOrgInfinispanV1Resource,
		infinispan_org_v2alpha1.NewInfinispanOrgBackupV2Alpha1Resource,
		infinispan_org_v2alpha1.NewInfinispanOrgBatchV2Alpha1Resource,
		infinispan_org_v2alpha1.NewInfinispanOrgCacheV2Alpha1Resource,
		infinispan_org_v2alpha1.NewInfinispanOrgRestoreV2Alpha1Resource,
		installation_mattermost_com_v1beta1.NewInstallationMattermostComMattermostV1Beta1Resource,
		iot_eclipse_org_v1alpha1.NewIotEclipseOrgDittoV1Alpha1Resource,
		iot_eclipse_org_v1alpha1.NewIotEclipseOrgHawkbitV1Alpha1Resource,
		jaegertracing_io_v1.NewJaegertracingIoJaegerV1Resource,
		jobsmanager_raczylo_com_v1beta1.NewJobsmanagerRaczyloComManagedJobV1Beta1Resource,
		k8gb_absa_oss_v1beta1.NewK8GbAbsaOssGslbV1Beta1Resource,
		k8s_otterize_com_v1alpha2.NewK8SOtterizeComClientIntentsV1Alpha2Resource,
		k8s_otterize_com_v1alpha2.NewK8SOtterizeComKafkaServerConfigV1Alpha2Resource,
		k8s_otterize_com_v1alpha2.NewK8SOtterizeComProtectedServiceV1Alpha2Resource,
		kafka_strimzi_io_v1alpha1.NewKafkaStrimziIoKafkaTopicV1Alpha1Resource,
		kafka_strimzi_io_v1alpha1.NewKafkaStrimziIoKafkaUserV1Alpha1Resource,
		kafka_strimzi_io_v1beta1.NewKafkaStrimziIoKafkaTopicV1Beta1Resource,
		kafka_strimzi_io_v1beta1.NewKafkaStrimziIoKafkaUserV1Beta1Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaBridgeV1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaConnectV1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaConnectorV1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaMirrorMaker2V1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaMirrorMakerV1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaRebalanceV1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaTopicV1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaUserV1Beta2Resource,
		kafka_strimzi_io_v1beta2.NewKafkaStrimziIoKafkaV1Beta2Resource,
		keda_sh_v1alpha1.NewKedaShClusterTriggerAuthenticationV1Alpha1Resource,
		keda_sh_v1alpha1.NewKedaShScaledJobV1Alpha1Resource,
		keda_sh_v1alpha1.NewKedaShScaledObjectV1Alpha1Resource,
		keda_sh_v1alpha1.NewKedaShTriggerAuthenticationV1Alpha1Resource,
		keycloak_org_v1alpha1.NewKeycloakOrgKeycloakBackupV1Alpha1Resource,
		keycloak_org_v1alpha1.NewKeycloakOrgKeycloakClientV1Alpha1Resource,
		keycloak_org_v1alpha1.NewKeycloakOrgKeycloakRealmV1Alpha1Resource,
		keycloak_org_v1alpha1.NewKeycloakOrgKeycloakUserV1Alpha1Resource,
		keycloak_org_v1alpha1.NewKeycloakOrgKeycloakV1Alpha1Resource,
		kiali_io_v1alpha1.NewKialiIoKialiV1Alpha1Resource,
		kibana_k8s_elastic_co_v1.NewKibanaK8SElasticCoKibanaV1Resource,
		kibana_k8s_elastic_co_v1beta1.NewKibanaK8SElasticCoKibanaV1Beta1Resource,
		kms_services_k8s_aws_v1alpha1.NewKmsServicesK8SAwsAliasV1Alpha1Resource,
		kms_services_k8s_aws_v1alpha1.NewKmsServicesK8SAwsGrantV1Alpha1Resource,
		kms_services_k8s_aws_v1alpha1.NewKmsServicesK8SAwsKeyV1Alpha1Resource,
		kubevious_io_v1alpha1.NewKubeviousIoWorkloadProfileV1Alpha1Resource,
		kubevious_io_v1alpha1.NewKubeviousIoWorkloadV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoCircuitBreakerV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoContainerPatchV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoDataplaneInsightV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoDataplaneV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoExternalServiceV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoFaultInjectionV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoHealthCheckV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshAccessLogV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshCircuitBreakerV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshFaultInjectionV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshGatewayConfigV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshGatewayInstanceV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshGatewayRouteV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshGatewayV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshHTTPRouteV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshHealthCheckV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshInsightV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshLoadBalancingStrategyV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshProxyPatchV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshRateLimitV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshRetryV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshTCPRouteV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshTimeoutV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshTraceV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshTrafficPermissionV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoMeshV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoProxyTemplateV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoRateLimitV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoRetryV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoServiceInsightV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoTimeoutV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoTrafficLogV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoTrafficPermissionV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoTrafficRouteV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoTrafficTraceV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoVirtualOutboundV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoZoneEgressInsightV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoZoneEgressV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoZoneIngressInsightV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoZoneIngressV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoZoneInsightV1Alpha1Resource,
		kuma_io_v1alpha1.NewKumaIoZoneV1Alpha1Resource,
		kustomize_toolkit_fluxcd_io_v1.NewKustomizeToolkitFluxcdIoKustomizationV1Resource,
		kustomize_toolkit_fluxcd_io_v1beta1.NewKustomizeToolkitFluxcdIoKustomizationV1Beta1Resource,
		kustomize_toolkit_fluxcd_io_v1beta2.NewKustomizeToolkitFluxcdIoKustomizationV1Beta2Resource,
		kyverno_io_v1.NewKyvernoIoClusterPolicyV1Resource,
		kyverno_io_v1.NewKyvernoIoPolicyV1Resource,
		kyverno_io_v1alpha2.NewKyvernoIoAdmissionReportV1Alpha2Resource,
		kyverno_io_v1alpha2.NewKyvernoIoBackgroundScanReportV1Alpha2Resource,
		kyverno_io_v1alpha2.NewKyvernoIoClusterAdmissionReportV1Alpha2Resource,
		kyverno_io_v1alpha2.NewKyvernoIoClusterBackgroundScanReportV1Alpha2Resource,
		kyverno_io_v1beta1.NewKyvernoIoUpdateRequestV1Beta1Resource,
		kyverno_io_v2alpha1.NewKyvernoIoCleanupPolicyV2Alpha1Resource,
		kyverno_io_v2alpha1.NewKyvernoIoClusterCleanupPolicyV2Alpha1Resource,
		kyverno_io_v2alpha1.NewKyvernoIoPolicyExceptionV2Alpha1Resource,
		kyverno_io_v2beta1.NewKyvernoIoClusterPolicyV2Beta1Resource,
		kyverno_io_v2beta1.NewKyvernoIoPolicyV2Beta1Resource,
		lambda_services_k8s_aws_v1alpha1.NewLambdaServicesK8SAwsAliasV1Alpha1Resource,
		lambda_services_k8s_aws_v1alpha1.NewLambdaServicesK8SAwsCodeSigningConfigV1Alpha1Resource,
		lambda_services_k8s_aws_v1alpha1.NewLambdaServicesK8SAwsEventSourceMappingV1Alpha1Resource,
		lambda_services_k8s_aws_v1alpha1.NewLambdaServicesK8SAwsFunctionURLConfigV1Alpha1Resource,
		lambda_services_k8s_aws_v1alpha1.NewLambdaServicesK8SAwsFunctionV1Alpha1Resource,
		lb_lbconfig_carlosedp_com_v1.NewLbLbconfigCarlosedpComExternalLoadBalancerV1Resource,
		lerentis_uploadfilter24_eu_v1beta4.NewLerentisUploadfilter24EuBitwardenSecretV1Beta4Resource,
		lerentis_uploadfilter24_eu_v1beta4.NewLerentisUploadfilter24EuBitwardenTemplateV1Beta4Resource,
		lerentis_uploadfilter24_eu_v1beta4.NewLerentisUploadfilter24EuRegistryCredentialV1Beta4Resource,
		litmuschaos_io_v1alpha1.NewLitmuschaosIoChaosEngineV1Alpha1Resource,
		litmuschaos_io_v1alpha1.NewLitmuschaosIoChaosExperimentV1Alpha1Resource,
		litmuschaos_io_v1alpha1.NewLitmuschaosIoChaosResultV1Alpha1Resource,
		logging_banzaicloud_io_v1alpha1.NewLoggingBanzaicloudIoClusterFlowV1Alpha1Resource,
		logging_banzaicloud_io_v1alpha1.NewLoggingBanzaicloudIoClusterOutputV1Alpha1Resource,
		logging_banzaicloud_io_v1alpha1.NewLoggingBanzaicloudIoFlowV1Alpha1Resource,
		logging_banzaicloud_io_v1alpha1.NewLoggingBanzaicloudIoLoggingV1Alpha1Resource,
		logging_banzaicloud_io_v1alpha1.NewLoggingBanzaicloudIoOutputV1Alpha1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoClusterFlowV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoClusterOutputV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoFlowV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoFluentbitAgentV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoLoggingV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoNodeAgentV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoOutputV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoSyslogNGClusterFlowV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoSyslogNGClusterOutputV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoSyslogNGFlowV1Beta1Resource,
		logging_banzaicloud_io_v1beta1.NewLoggingBanzaicloudIoSyslogNGOutputV1Beta1Resource,
		logging_extensions_banzaicloud_io_v1alpha1.NewLoggingExtensionsBanzaicloudIoEventTailerV1Alpha1Resource,
		logging_extensions_banzaicloud_io_v1alpha1.NewLoggingExtensionsBanzaicloudIoHostTailerV1Alpha1Resource,
		loki_grafana_com_v1.NewLokiGrafanaComAlertingRuleV1Resource,
		loki_grafana_com_v1.NewLokiGrafanaComLokiStackV1Resource,
		loki_grafana_com_v1.NewLokiGrafanaComRecordingRuleV1Resource,
		loki_grafana_com_v1.NewLokiGrafanaComRulerConfigV1Resource,
		loki_grafana_com_v1beta1.NewLokiGrafanaComAlertingRuleV1Beta1Resource,
		loki_grafana_com_v1beta1.NewLokiGrafanaComLokiStackV1Beta1Resource,
		loki_grafana_com_v1beta1.NewLokiGrafanaComRecordingRuleV1Beta1Resource,
		loki_grafana_com_v1beta1.NewLokiGrafanaComRulerConfigV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoBackingImageDataSourceV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoBackingImageManagerV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoBackingImageV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoBackupTargetV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoBackupV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoBackupVolumeV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoEngineImageV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoEngineV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoInstanceManagerV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoNodeV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoRecurringJobV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoReplicaV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoSettingV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoShareManagerV1Beta1Resource,
		longhorn_io_v1beta1.NewLonghornIoVolumeV1Beta1Resource,
		longhorn_io_v1beta2.NewLonghornIoBackingImageDataSourceV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoBackingImageManagerV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoBackingImageV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoBackupTargetV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoBackupV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoBackupVolumeV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoEngineImageV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoEngineV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoInstanceManagerV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoNodeV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoOrphanV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoRecurringJobV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoReplicaV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoSettingV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoShareManagerV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoSnapshotV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoSupportBundleV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoSystemBackupV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoSystemRestoreV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoVolumeAttachmentV1Beta2Resource,
		longhorn_io_v1beta2.NewLonghornIoVolumeV1Beta2Resource,
		maps_k8s_elastic_co_v1alpha1.NewMapsK8SElasticCoElasticMapsServerV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoBackupV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoConnectionV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoDatabaseV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoGrantV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoMariaDBV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoRestoreV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoSqlJobV1Alpha1Resource,
		mariadb_mmontes_io_v1alpha1.NewMariadbMmontesIoUserV1Alpha1Resource,
		mattermost_com_v1alpha1.NewMattermostComClusterInstallationV1Alpha1Resource,
		mattermost_com_v1alpha1.NewMattermostComMattermostRestoreDBV1Alpha1Resource,
		metacontroller_k8s_io_v1alpha1.NewMetacontrollerK8SIoCompositeControllerV1Alpha1Resource,
		metacontroller_k8s_io_v1alpha1.NewMetacontrollerK8SIoControllerRevisionV1Alpha1Resource,
		metacontroller_k8s_io_v1alpha1.NewMetacontrollerK8SIoDecoratorControllerV1Alpha1Resource,
		metal3_io_v1alpha1.NewMetal3IoBMCEventSubscriptionV1Alpha1Resource,
		metal3_io_v1alpha1.NewMetal3IoBareMetalHostV1Alpha1Resource,
		metal3_io_v1alpha1.NewMetal3IoFirmwareSchemaV1Alpha1Resource,
		metal3_io_v1alpha1.NewMetal3IoHardwareDataV1Alpha1Resource,
		metal3_io_v1alpha1.NewMetal3IoHostFirmwareSettingsV1Alpha1Resource,
		metal3_io_v1alpha1.NewMetal3IoPreprovisioningImageV1Alpha1Resource,
		minio_min_io_v2.NewMinioMinIoTenantV2Resource,
		mirrors_kts_studio_v1alpha1.NewMirrorsKtsStudioSecretMirrorV1Alpha1Resource,
		mirrors_kts_studio_v1alpha2.NewMirrorsKtsStudioSecretMirrorV1Alpha2Resource,
		model_kubedl_io_v1alpha1.NewModelKubedlIoModelV1Alpha1Resource,
		model_kubedl_io_v1alpha1.NewModelKubedlIoModelVersionV1Alpha1Resource,
		monitoring_coreos_com_v1.NewMonitoringCoreosComAlertmanagerV1Resource,
		monitoring_coreos_com_v1.NewMonitoringCoreosComPodMonitorV1Resource,
		monitoring_coreos_com_v1.NewMonitoringCoreosComProbeV1Resource,
		monitoring_coreos_com_v1.NewMonitoringCoreosComPrometheusRuleV1Resource,
		monitoring_coreos_com_v1.NewMonitoringCoreosComPrometheusV1Resource,
		monitoring_coreos_com_v1.NewMonitoringCoreosComServiceMonitorV1Resource,
		monitoring_coreos_com_v1.NewMonitoringCoreosComThanosRulerV1Resource,
		monitoring_coreos_com_v1alpha1.NewMonitoringCoreosComAlertmanagerConfigV1Alpha1Resource,
		monitoring_coreos_com_v1alpha1.NewMonitoringCoreosComPrometheusAgentV1Alpha1Resource,
		monitoring_coreos_com_v1alpha1.NewMonitoringCoreosComScrapeConfigV1Alpha1Resource,
		mq_services_k8s_aws_v1alpha1.NewMqServicesK8SAwsBrokerV1Alpha1Resource,
		multicluster_x_k8s_io_v1alpha1.NewMulticlusterXK8SIoServiceImportV1Alpha1Resource,
		multicluster_x_k8s_io_v1alpha1.NewMulticlusterXK8SIoServiceImportV1Alpha1Resource,
		mutations_gatekeeper_sh_v1.NewMutationsGatekeeperShAssignMetadataV1Resource,
		mutations_gatekeeper_sh_v1.NewMutationsGatekeeperShAssignV1Resource,
		mutations_gatekeeper_sh_v1.NewMutationsGatekeeperShModifySetV1Resource,
		mutations_gatekeeper_sh_v1alpha1.NewMutationsGatekeeperShAssignImageV1Alpha1Resource,
		mutations_gatekeeper_sh_v1alpha1.NewMutationsGatekeeperShAssignMetadataV1Alpha1Resource,
		mutations_gatekeeper_sh_v1alpha1.NewMutationsGatekeeperShAssignV1Alpha1Resource,
		mutations_gatekeeper_sh_v1alpha1.NewMutationsGatekeeperShModifySetV1Alpha1Resource,
		mutations_gatekeeper_sh_v1beta1.NewMutationsGatekeeperShAssignMetadataV1Beta1Resource,
		mutations_gatekeeper_sh_v1beta1.NewMutationsGatekeeperShAssignV1Beta1Resource,
		mutations_gatekeeper_sh_v1beta1.NewMutationsGatekeeperShModifySetV1Beta1Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoDestinationRuleV1Alpha3Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoEnvoyFilterV1Alpha3Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoGatewayV1Alpha3Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoServiceEntryV1Alpha3Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoSidecarV1Alpha3Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoVirtualServiceV1Alpha3Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoWorkloadEntryV1Alpha3Resource,
		networking_istio_io_v1alpha3.NewNetworkingIstioIoWorkloadGroupV1Alpha3Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoDestinationRuleV1Beta1Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoGatewayV1Beta1Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoProxyConfigV1Beta1Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoServiceEntryV1Beta1Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoSidecarV1Beta1Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoVirtualServiceV1Beta1Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoWorkloadEntryV1Beta1Resource,
		networking_istio_io_v1beta1.NewNetworkingIstioIoWorkloadGroupV1Beta1Resource,
		networking_karmada_io_v1alpha1.NewNetworkingKarmadaIoMultiClusterIngressV1Alpha1Resource,
		networking_karmada_io_v1alpha1.NewNetworkingKarmadaIoMultiClusterServiceV1Alpha1Resource,
		nfd_k8s_sigs_io_v1alpha1.NewNfdK8SSigsIoNodeFeatureRuleV1Alpha1Resource,
		nodeinfo_volcano_sh_v1alpha1.NewNodeinfoVolcanoShNumatopologyV1Alpha1Resource,
		notebook_kubedl_io_v1alpha1.NewNotebookKubedlIoNotebookV1Alpha1Resource,
		notification_toolkit_fluxcd_io_v1.NewNotificationToolkitFluxcdIoReceiverV1Resource,
		notification_toolkit_fluxcd_io_v1beta1.NewNotificationToolkitFluxcdIoAlertV1Beta1Resource,
		notification_toolkit_fluxcd_io_v1beta1.NewNotificationToolkitFluxcdIoProviderV1Beta1Resource,
		notification_toolkit_fluxcd_io_v1beta1.NewNotificationToolkitFluxcdIoReceiverV1Beta1Resource,
		notification_toolkit_fluxcd_io_v1beta2.NewNotificationToolkitFluxcdIoAlertV1Beta2Resource,
		notification_toolkit_fluxcd_io_v1beta2.NewNotificationToolkitFluxcdIoProviderV1Beta2Resource,
		notification_toolkit_fluxcd_io_v1beta2.NewNotificationToolkitFluxcdIoReceiverV1Beta2Resource,
		objectbucket_io_v1alpha1.NewObjectbucketIoObjectBucketClaimV1Alpha1Resource,
		objectbucket_io_v1alpha1.NewObjectbucketIoObjectBucketV1Alpha1Resource,
		opensearchservice_services_k8s_aws_v1alpha1.NewOpensearchserviceServicesK8SAwsDomainV1Alpha1Resource,
		opentelemetry_io_v1alpha1.NewOpentelemetryIoInstrumentationV1Alpha1Resource,
		opentelemetry_io_v1alpha1.NewOpentelemetryIoOpenTelemetryCollectorV1Alpha1Resource,
		operations_kubeedge_io_v1alpha1.NewOperationsKubeedgeIoNodeUpgradeJobV1Alpha1Resource,
		operator_aquasec_com_v1alpha1.NewOperatorAquasecComAquaCspV1Alpha1Resource,
		operator_aquasec_com_v1alpha1.NewOperatorAquasecComAquaDatabaseV1Alpha1Resource,
		operator_aquasec_com_v1alpha1.NewOperatorAquasecComAquaEnforcerV1Alpha1Resource,
		operator_aquasec_com_v1alpha1.NewOperatorAquasecComAquaGatewayV1Alpha1Resource,
		operator_aquasec_com_v1alpha1.NewOperatorAquasecComAquaKubeEnforcerV1Alpha1Resource,
		operator_aquasec_com_v1alpha1.NewOperatorAquasecComAquaScannerV1Alpha1Resource,
		operator_aquasec_com_v1alpha1.NewOperatorAquasecComAquaServerV1Alpha1Resource,
		operator_cryostat_io_v1beta1.NewOperatorCryostatIoCryostatV1Beta1Resource,
		operator_knative_dev_v1beta1.NewOperatorKnativeDevKnativeEventingV1Beta1Resource,
		operator_knative_dev_v1beta1.NewOperatorKnativeDevKnativeServingV1Beta1Resource,
		operator_open_cluster_management_io_v1.NewOperatorOpenClusterManagementIoClusterManagerV1Resource,
		operator_open_cluster_management_io_v1.NewOperatorOpenClusterManagementIoKlusterletV1Resource,
		operator_tigera_io_v1.NewOperatorTigeraIoAPIServerV1Resource,
		operator_tigera_io_v1.NewOperatorTigeraIoImageSetV1Resource,
		operator_tigera_io_v1.NewOperatorTigeraIoInstallationV1Resource,
		operator_tigera_io_v1.NewOperatorTigeraIoTigeraStatusV1Resource,
		org_eclipse_che_v1.NewOrgEclipseCheCheClusterV1Resource,
		org_eclipse_che_v2.NewOrgEclipseCheCheClusterV2Resource,
		pkg_crossplane_io_v1.NewPkgCrossplaneIoConfigurationRevisionV1Resource,
		pkg_crossplane_io_v1.NewPkgCrossplaneIoConfigurationV1Resource,
		pkg_crossplane_io_v1.NewPkgCrossplaneIoProviderRevisionV1Resource,
		pkg_crossplane_io_v1.NewPkgCrossplaneIoProviderV1Resource,
		pkg_crossplane_io_v1alpha1.NewPkgCrossplaneIoControllerConfigV1Alpha1Resource,
		pkg_crossplane_io_v1beta1.NewPkgCrossplaneIoLockV1Beta1Resource,
		policy_clusterpedia_io_v1alpha1.NewPolicyClusterpediaIoClusterImportPolicyV1Alpha1Resource,
		policy_clusterpedia_io_v1alpha1.NewPolicyClusterpediaIoPediaClusterLifecycleV1Alpha1Resource,
		policy_karmada_io_v1alpha1.NewPolicyKarmadaIoClusterOverridePolicyV1Alpha1Resource,
		policy_karmada_io_v1alpha1.NewPolicyKarmadaIoClusterPropagationPolicyV1Alpha1Resource,
		policy_karmada_io_v1alpha1.NewPolicyKarmadaIoFederatedResourceQuotaV1Alpha1Resource,
		policy_karmada_io_v1alpha1.NewPolicyKarmadaIoOverridePolicyV1Alpha1Resource,
		policy_karmada_io_v1alpha1.NewPolicyKarmadaIoPropagationPolicyV1Alpha1Resource,
		postgres_operator_crunchydata_com_v1beta1.NewPostgresOperatorCrunchydataComPostgresClusterV1Beta1Resource,
		prometheusservice_services_k8s_aws_v1alpha1.NewPrometheusserviceServicesK8SAwsAlertManagerDefinitionV1Alpha1Resource,
		prometheusservice_services_k8s_aws_v1alpha1.NewPrometheusserviceServicesK8SAwsRuleGroupsNamespaceV1Alpha1Resource,
		prometheusservice_services_k8s_aws_v1alpha1.NewPrometheusserviceServicesK8SAwsWorkspaceV1Alpha1Resource,
		quay_redhat_com_v1.NewQuayRedhatComQuayRegistryV1Resource,
		rds_services_k8s_aws_v1alpha1.NewRdsServicesK8SAwsDBClusterParameterGroupV1Alpha1Resource,
		rds_services_k8s_aws_v1alpha1.NewRdsServicesK8SAwsDBClusterV1Alpha1Resource,
		rds_services_k8s_aws_v1alpha1.NewRdsServicesK8SAwsDBInstanceV1Alpha1Resource,
		rds_services_k8s_aws_v1alpha1.NewRdsServicesK8SAwsDBParameterGroupV1Alpha1Resource,
		rds_services_k8s_aws_v1alpha1.NewRdsServicesK8SAwsDBProxyV1Alpha1Resource,
		rds_services_k8s_aws_v1alpha1.NewRdsServicesK8SAwsDBSubnetGroupV1Alpha1Resource,
		rds_services_k8s_aws_v1alpha1.NewRdsServicesK8SAwsGlobalClusterV1Alpha1Resource,
		redhatcop_redhat_io_v1alpha1.NewRedhatcopRedhatIoGroupConfigV1Alpha1Resource,
		redhatcop_redhat_io_v1alpha1.NewRedhatcopRedhatIoNamespaceConfigV1Alpha1Resource,
		redhatcop_redhat_io_v1alpha1.NewRedhatcopRedhatIoUserConfigV1Alpha1Resource,
		registry_apicur_io_v1.NewRegistryApicurIoApicurioRegistryV1Resource,
		reliablesyncs_kubeedge_io_v1alpha1.NewReliablesyncsKubeedgeIoClusterObjectSyncV1Alpha1Resource,
		reliablesyncs_kubeedge_io_v1alpha1.NewReliablesyncsKubeedgeIoObjectSyncV1Alpha1Resource,
		resources_teleport_dev_v1.NewResourcesTeleportDevTeleportLoginRuleV1Resource,
		resources_teleport_dev_v1.NewResourcesTeleportDevTeleportOktaImportRuleV1Resource,
		resources_teleport_dev_v2.NewResourcesTeleportDevTeleportProvisionTokenV2Resource,
		resources_teleport_dev_v2.NewResourcesTeleportDevTeleportSAMLConnectorV2Resource,
		resources_teleport_dev_v2.NewResourcesTeleportDevTeleportUserV2Resource,
		resources_teleport_dev_v3.NewResourcesTeleportDevTeleportGithubConnectorV3Resource,
		resources_teleport_dev_v3.NewResourcesTeleportDevTeleportOIDCConnectorV3Resource,
		resources_teleport_dev_v5.NewResourcesTeleportDevTeleportRoleV5Resource,
		resources_teleport_dev_v6.NewResourcesTeleportDevTeleportRoleV6Resource,
		ripsaw_cloudbulldozer_io_v1alpha1.NewRipsawCloudbulldozerIoBenchmarkV1Alpha1Resource,
		rocketmq_apache_org_v1alpha1.NewRocketmqApacheOrgBrokerV1Alpha1Resource,
		rocketmq_apache_org_v1alpha1.NewRocketmqApacheOrgConsoleV1Alpha1Resource,
		rocketmq_apache_org_v1alpha1.NewRocketmqApacheOrgNameServiceV1Alpha1Resource,
		rocketmq_apache_org_v1alpha1.NewRocketmqApacheOrgTopicTransferV1Alpha1Resource,
		rules_kubeedge_io_v1.NewRulesKubeedgeIoRuleEndpointV1Resource,
		rules_kubeedge_io_v1.NewRulesKubeedgeIoRuleV1Resource,
		s3_services_k8s_aws_v1alpha1.NewS3ServicesK8SAwsBucketV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsAppV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsDataQualityJobDefinitionV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsDomainV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsEndpointConfigV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsEndpointV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsFeatureGroupV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsHyperParameterTuningJobV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsModelBiasJobDefinitionV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsModelExplainabilityJobDefinitionV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsModelPackageGroupV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsModelPackageV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsModelQualityJobDefinitionV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsModelV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsMonitoringScheduleV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsNotebookInstanceLifecycleConfigV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsNotebookInstanceV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsProcessingJobV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsTrainingJobV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsTransformJobV1Alpha1Resource,
		sagemaker_services_k8s_aws_v1alpha1.NewSagemakerServicesK8SAwsUserProfileV1Alpha1Resource,
		scheduling_koordinator_sh_v1alpha1.NewSchedulingKoordinatorShDeviceV1Alpha1Resource,
		scheduling_koordinator_sh_v1alpha1.NewSchedulingKoordinatorShPodMigrationJobV1Alpha1Resource,
		scheduling_koordinator_sh_v1alpha1.NewSchedulingKoordinatorShReservationV1Alpha1Resource,
		scheduling_sigs_k8s_io_v1alpha1.NewSchedulingSigsK8SIoElasticQuotaV1Alpha1Resource,
		scheduling_sigs_k8s_io_v1alpha1.NewSchedulingSigsK8SIoPodGroupV1Alpha1Resource,
		scheduling_volcano_sh_v1beta1.NewSchedulingVolcanoShPodGroupV1Beta1Resource,
		scheduling_volcano_sh_v1beta1.NewSchedulingVolcanoShQueueV1Beta1Resource,
		schemas_schemahero_io_v1alpha4.NewSchemasSchemaheroIoDataTypeV1Alpha4Resource,
		schemas_schemahero_io_v1alpha4.NewSchemasSchemaheroIoMigrationV1Alpha4Resource,
		schemas_schemahero_io_v1alpha4.NewSchemasSchemaheroIoTableV1Alpha4Resource,
		scylla_scylladb_com_v1.NewScyllaScylladbComScyllaClusterV1Resource,
		scylla_scylladb_com_v1alpha1.NewScyllaScylladbComNodeConfigV1Alpha1Resource,
		scylla_scylladb_com_v1alpha1.NewScyllaScylladbComScyllaOperatorConfigV1Alpha1Resource,
		secretgenerator_mittwald_de_v1alpha1.NewSecretgeneratorMittwaldDeBasicAuthV1Alpha1Resource,
		secretgenerator_mittwald_de_v1alpha1.NewSecretgeneratorMittwaldDeSSHKeyPairV1Alpha1Resource,
		secretgenerator_mittwald_de_v1alpha1.NewSecretgeneratorMittwaldDeStringSecretV1Alpha1Resource,
		secrets_crossplane_io_v1alpha1.NewSecretsCrossplaneIoStoreConfigV1Alpha1Resource,
		secscan_quay_redhat_com_v1alpha1.NewSecscanQuayRedhatComImageManifestVulnV1Alpha1Resource,
		security_istio_io_v1.NewSecurityIstioIoAuthorizationPolicyV1Resource,
		security_istio_io_v1.NewSecurityIstioIoRequestAuthenticationV1Resource,
		security_istio_io_v1beta1.NewSecurityIstioIoAuthorizationPolicyV1Beta1Resource,
		security_istio_io_v1beta1.NewSecurityIstioIoPeerAuthenticationV1Beta1Resource,
		security_istio_io_v1beta1.NewSecurityIstioIoRequestAuthenticationV1Beta1Resource,
		security_profiles_operator_x_k8s_io_v1alpha1.NewSecurityProfilesOperatorXK8SIoAppArmorProfileV1Alpha1Resource,
		security_profiles_operator_x_k8s_io_v1alpha1.NewSecurityProfilesOperatorXK8SIoProfileBindingV1Alpha1Resource,
		security_profiles_operator_x_k8s_io_v1alpha1.NewSecurityProfilesOperatorXK8SIoProfileRecordingV1Alpha1Resource,
		security_profiles_operator_x_k8s_io_v1alpha1.NewSecurityProfilesOperatorXK8SIoSecurityProfileNodeStatusV1Alpha1Resource,
		security_profiles_operator_x_k8s_io_v1alpha1.NewSecurityProfilesOperatorXK8SIoSecurityProfilesOperatorDaemonV1Alpha1Resource,
		security_profiles_operator_x_k8s_io_v1alpha2.NewSecurityProfilesOperatorXK8SIoRawSelinuxProfileV1Alpha2Resource,
		security_profiles_operator_x_k8s_io_v1alpha2.NewSecurityProfilesOperatorXK8SIoSelinuxProfileV1Alpha2Resource,
		security_profiles_operator_x_k8s_io_v1beta1.NewSecurityProfilesOperatorXK8SIoSeccompProfileV1Beta1Resource,
		sematext_com_v1.NewSematextComSematextAgentV1Resource,
		servicebinding_io_v1alpha3.NewServicebindingIoClusterWorkloadResourceMappingV1Alpha3Resource,
		servicebinding_io_v1alpha3.NewServicebindingIoServiceBindingV1Alpha3Resource,
		servicebinding_io_v1beta1.NewServicebindingIoClusterWorkloadResourceMappingV1Beta1Resource,
		servicebinding_io_v1beta1.NewServicebindingIoServiceBindingV1Beta1Resource,
		services_k8s_aws_v1alpha1.NewServicesK8SAwsAdoptedResourceV1Alpha1Resource,
		services_k8s_aws_v1alpha1.NewServicesK8SAwsFieldExportV1Alpha1Resource,
		serving_kubedl_io_v1alpha1.NewServingKubedlIoInferenceV1Alpha1Resource,
		sfn_services_k8s_aws_v1alpha1.NewSfnServicesK8SAwsActivityV1Alpha1Resource,
		sfn_services_k8s_aws_v1alpha1.NewSfnServicesK8SAwsStateMachineV1Alpha1Resource,
		site_superedge_io_v1alpha1.NewSiteSuperedgeIoNodeGroupV1Alpha1Resource,
		site_superedge_io_v1alpha1.NewSiteSuperedgeIoNodeUnitV1Alpha1Resource,
		slo_koordinator_sh_v1alpha1.NewSloKoordinatorShNodeMetricV1Alpha1Resource,
		slo_koordinator_sh_v1alpha1.NewSloKoordinatorShNodeSLOV1Alpha1Resource,
		source_toolkit_fluxcd_io_v1.NewSourceToolkitFluxcdIoGitRepositoryV1Resource,
		source_toolkit_fluxcd_io_v1beta1.NewSourceToolkitFluxcdIoBucketV1Beta1Resource,
		source_toolkit_fluxcd_io_v1beta1.NewSourceToolkitFluxcdIoGitRepositoryV1Beta1Resource,
		source_toolkit_fluxcd_io_v1beta1.NewSourceToolkitFluxcdIoHelmChartV1Beta1Resource,
		source_toolkit_fluxcd_io_v1beta1.NewSourceToolkitFluxcdIoHelmRepositoryV1Beta1Resource,
		source_toolkit_fluxcd_io_v1beta2.NewSourceToolkitFluxcdIoBucketV1Beta2Resource,
		source_toolkit_fluxcd_io_v1beta2.NewSourceToolkitFluxcdIoGitRepositoryV1Beta2Resource,
		source_toolkit_fluxcd_io_v1beta2.NewSourceToolkitFluxcdIoHelmChartV1Beta2Resource,
		source_toolkit_fluxcd_io_v1beta2.NewSourceToolkitFluxcdIoHelmRepositoryV1Beta2Resource,
		source_toolkit_fluxcd_io_v1beta2.NewSourceToolkitFluxcdIoOCIRepositoryV1Beta2Resource,
		sparkoperator_k8s_io_v1beta2.NewSparkoperatorK8SIoScheduledSparkApplicationV1Beta2Resource,
		sparkoperator_k8s_io_v1beta2.NewSparkoperatorK8SIoSparkApplicationV1Beta2Resource,
		stunner_l7mp_io_v1alpha1.NewStunnerL7MpIoGatewayConfigV1Alpha1Resource,
		telemetry_istio_io_v1alpha1.NewTelemetryIstioIoTelemetryV1Alpha1Resource,
		templates_gatekeeper_sh_v1.NewTemplatesGatekeeperShConstraintTemplateV1Resource,
		templates_gatekeeper_sh_v1alpha1.NewTemplatesGatekeeperShConstraintTemplateV1Alpha1Resource,
		templates_gatekeeper_sh_v1beta1.NewTemplatesGatekeeperShConstraintTemplateV1Beta1Resource,
		tests_testkube_io_v1.NewTestsTestkubeIoScriptV1Resource,
		tests_testkube_io_v1.NewTestsTestkubeIoTestExecutionV1Resource,
		tests_testkube_io_v1.NewTestsTestkubeIoTestSourceV1Resource,
		tests_testkube_io_v1.NewTestsTestkubeIoTestSuiteExecutionV1Resource,
		tests_testkube_io_v1.NewTestsTestkubeIoTestSuiteV1Resource,
		tests_testkube_io_v1.NewTestsTestkubeIoTestTriggerV1Resource,
		tests_testkube_io_v1.NewTestsTestkubeIoTestV1Resource,
		tests_testkube_io_v2.NewTestsTestkubeIoScriptV2Resource,
		tests_testkube_io_v2.NewTestsTestkubeIoTestSuiteV2Resource,
		tests_testkube_io_v2.NewTestsTestkubeIoTestV2Resource,
		tests_testkube_io_v3.NewTestsTestkubeIoTestSuiteV3Resource,
		tests_testkube_io_v3.NewTestsTestkubeIoTestV3Resource,
		topology_node_k8s_io_v1alpha1.NewTopologyNodeK8SIoNodeResourceTopologyV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoIngressRouteTCPV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoIngressRouteUDPV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoIngressRouteV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoMiddlewareTCPV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoMiddlewareV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoServersTransportTCPV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoServersTransportV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoTLSOptionV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoTLSStoreV1Alpha1Resource,
		traefik_io_v1alpha1.NewTraefikIoTraefikServiceV1Alpha1Resource,
		training_kubedl_io_v1alpha1.NewTrainingKubedlIoElasticDLJobV1Alpha1Resource,
		training_kubedl_io_v1alpha1.NewTrainingKubedlIoMPIJobV1Alpha1Resource,
		training_kubedl_io_v1alpha1.NewTrainingKubedlIoMarsJobV1Alpha1Resource,
		training_kubedl_io_v1alpha1.NewTrainingKubedlIoPyTorchJobV1Alpha1Resource,
		training_kubedl_io_v1alpha1.NewTrainingKubedlIoTFJobV1Alpha1Resource,
		training_kubedl_io_v1alpha1.NewTrainingKubedlIoXDLJobV1Alpha1Resource,
		training_kubedl_io_v1alpha1.NewTrainingKubedlIoXGBoostJobV1Alpha1Resource,
		virt_virtink_smartx_com_v1alpha1.NewVirtVirtinkSmartxComVirtualMachineMigrationV1Alpha1Resource,
		virt_virtink_smartx_com_v1alpha1.NewVirtVirtinkSmartxComVirtualMachineV1Alpha1Resource,
		wgpolicyk8s_io_v1alpha2.NewWgpolicyk8SIoClusterPolicyReportV1Alpha2Resource,
		wgpolicyk8s_io_v1alpha2.NewWgpolicyk8SIoPolicyReportV1Alpha2Resource,
		wildfly_org_v1alpha1.NewWildflyOrgWildFlyServerV1Alpha1Resource,
		work_karmada_io_v1alpha1.NewWorkKarmadaIoClusterResourceBindingV1Alpha1Resource,
		work_karmada_io_v1alpha1.NewWorkKarmadaIoResourceBindingV1Alpha1Resource,
		work_karmada_io_v1alpha1.NewWorkKarmadaIoWorkV1Alpha1Resource,
		work_karmada_io_v1alpha2.NewWorkKarmadaIoClusterResourceBindingV1Alpha2Resource,
		work_karmada_io_v1alpha2.NewWorkKarmadaIoResourceBindingV1Alpha2Resource,
	}
}
