# SPDX-FileCopyrightText: The terraform-provider-k8s Authors
# SPDX-License-Identifier: 0BSD

name: FluentdFluentIoClusterOutputV1Alpha1Manifest
on:
  pull_request:
    branches: [ main ]
    paths:
      - examples/data-sources/k8s_fluentd_fluent_io_cluster_output_v1alpha1_manifest/**
      - internal/provider/fluentd_fluent_io_v1alpha1/fluentd_fluent_io_cluster_output_v1alpha1_manifest.go
      - internal/provider/fluentd_fluent_io_v1alpha1/fluentd_fluent_io_cluster_output_v1alpha1_manifest_test.go
      - terratest/fluentd_fluent_io_v1alpha1/fluentd_fluent_io_cluster_output_v1alpha1_manifest_test.go
jobs:
  terraform:
    name: Test with Terraform
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v5
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - id: setup_terraform
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - id: install
        name: Install Provider
        run: make install
      - id: tests
        name: Run Unit Tests
        run: go test -v -timeout=120s -count=1 ./internal/provider/fluentd_fluent_io_v1alpha1/fluentd_fluent_io_cluster_output_v1alpha1_manifest_test.go
      - id: terratest
        name: Run Terratest Tests
        run: go test -v -timeout=120s -count=1 -run TestFluentdFluentIoClusterOutputV1Alpha1Manifest ./terratest/fluentd_fluent_io_v1alpha1
