# SPDX-FileCopyrightText: The terraform-provider-k8s Authors
# SPDX-License-Identifier: 0BSD

name: ConsoleOpenshiftIoConsoleClidownloadV1Manifest
on:
  pull_request:
    branches: [ main ]
    paths:
      - examples/data-sources/k8s_console_openshift_io_console_cli_download_v1_manifest/**
      - internal/provider/console_openshift_io_v1/console_openshift_io_console_cli_download_v1_manifest.go
      - internal/provider/console_openshift_io_v1/console_openshift_io_console_cli_download_v1_manifest_test.go
      - terratest/console_openshift_io_v1/console_openshift_io_console_cli_download_v1_manifest_test.go
jobs:
  terratest:
    name: Test with Terraform ${{ matrix.terraform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        terraform:
          - 1.4.*
          - 1.5.*
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - id: setup_terraform
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - id: install
        name: Install Provider
        run: make install
      - id: tests
        name: Run Unit Tests
        run: go test -v -timeout=120s -count=1 ./internal/provider/console_openshift_io_v1/console_openshift_io_console_cli_download_v1_manifest_test.go
      - id: terratest
        name: Run Terratest Tests
        run: go test -v -timeout=120s -count=1 -run TestConsoleOpenshiftIoConsoleClidownloadV1Manifest ./terratest/console_openshift_io_v1
