# SPDX-FileCopyrightText: The terraform-provider-k8s Authors
# SPDX-License-Identifier: 0BSD

name: GatewayNetworkingK8SIoReferenceGrantV1Alpha2DataSource
on:
  pull_request:
    branches: [ main ]
    paths:
      - examples/data-sources/k8s_gateway_networking_k8s_io_reference_grant_v1alpha2/**
      - internal/provider/gateway_networking_k8s_io_v1alpha2/gateway_networking_k8s_io_reference_grant_v1alpha2_data_source.go
      - internal/provider/gateway_networking_k8s_io_v1alpha2/gateway_networking_k8s_io_reference_grant_v1alpha2_data_source_test.go
      - terratest/gateway_networking_k8s_io_v1alpha2/gateway_networking_k8s_io_reference_grant_v1alpha2_data_source_test.go
jobs:
  terratest:
    name: Test with Terraform ${{ matrix.terraform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        terraform:
          - 1.4.*
          - 1.5.*
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - id: setup_terraform
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - id: install
        name: Install Provider
        run: make install
      - id: tests
        name: Run Unit Tests
        run: go test -v -timeout=120s -count=1 ./internal/provider/gateway_networking_k8s_io_v1alpha2/gateway_networking_k8s_io_reference_grant_v1alpha2_data_source_test.go
      - id: terratest
        name: Run Terratest Tests
        run: go test -v -timeout=120s -count=1 -run TestGatewayNetworkingK8SIoReferenceGrantV1Alpha2DataSource ./terratest/gateway_networking_k8s_io_v1alpha2
