# SPDX-FileCopyrightText: The terraform-provider-k8s Authors
# SPDX-License-Identifier: 0BSD

name: EnterprisesearchK8SElasticCoEnterpriseSearchV1Beta1Manifest
on:
  pull_request:
    branches: [ main ]
    paths:
      - examples/data-sources/k8s_enterprisesearch_k8s_elastic_co_enterprise_search_v1beta1_manifest/**
      - internal/provider/enterprisesearch_k8s_elastic_co_v1beta1/enterprisesearch_k8s_elastic_co_enterprise_search_v1beta1_manifest.go
      - internal/provider/enterprisesearch_k8s_elastic_co_v1beta1/enterprisesearch_k8s_elastic_co_enterprise_search_v1beta1_manifest_test.go
      - terratest/enterprisesearch_k8s_elastic_co_v1beta1/enterprisesearch_k8s_elastic_co_enterprise_search_v1beta1_manifest_test.go
jobs:
  terraform:
    name: Test with Terraform
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - id: setup_terraform
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - id: install
        name: Install Provider
        run: make install
      - id: tests
        name: Run Unit Tests
        run: go test -v -timeout=120s -count=1 ./internal/provider/enterprisesearch_k8s_elastic_co_v1beta1/enterprisesearch_k8s_elastic_co_enterprise_search_v1beta1_manifest_test.go
      - id: terratest
        name: Run Terratest Tests
        run: go test -v -timeout=120s -count=1 -run TestEnterprisesearchK8SElasticCoEnterpriseSearchV1Beta1Manifest ./terratest/enterprisesearch_k8s_elastic_co_v1beta1
