# SPDX-FileCopyrightText: The terraform-provider-k8s Authors
# SPDX-License-Identifier: 0BSD

name: Update Upstream Specs
on:
  schedule:
    - cron: 49 13 * * FRI
  workflow_dispatch:
jobs:
  update:
    name: Update Specs
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - id: fetch
        name: Fetch Specs
        run: make fetch
      - id: generate
        name: Generate Code
        run: make generate
        continue-on-error: true
      - id: docs
        name: Generate Documentation
        run: make docs
        continue-on-error: true
      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update upstream specifications to their latest version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update upstream specifications to their latest version
          body: |
            - `make fetch`: ${{ steps.fetch.outcome }}
            - `make generate`: ${{ steps.generate.outcome }}
            - `make docs`: ${{ steps.docs.outcome }}
          labels: enhancement
          assignees: sebhoss
          draft: false
          base: main
          branch: update-specs
          delete-branch: true
      - id: automerge
        name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
